In [1]:
import cv2
import numpy as np

In [2]:
# read class name from file

class_name = []
class_file = "../models/ssd_mobilenet_v3/coco.names"
with open(class_file, 'rt') as f:
    class_name = f.read().rstrip("\n").split("\n")
print(class_name[76])

cell phone


In [3]:
# load config and weight and instantiate the model

config = "../models/ssd_mobilenet_v3/ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt"
weights = "../models/ssd_mobilenet_v3/frozen_inference_graph.pb"

net = cv2.dnn_DetectionModel(weights, config)

# configure input for pretrained mdoel
net.setInputSize(320, 320)
net.setInputScale(1.0/127.5)
net.setInputMean((127.5, 127.5, 127.5))
net.setInputSwapRB(True)

<dnn_Model 0x7fbf396afe30>

In [124]:
cap.release()
cv2.destroyAllWindows()

In [ ]:
#cap = cv2.VideoCapture("../media/video/face_elena.mp4")
cap = cv2.VideoCapture(1)
cap.set(3, 640)
cap.set(4, 480)

while cap.isOpened():
    ret, frame = cap.read()
    frame = cv2.resize(frame, (640, 480))
    #frame = cv2.flip(frame, 0)
    #frame = cv2.flip(frame, 1)
    
    # get detection
    class_ids, conf, bbox = net.detect(frame, confThreshold=0.1)
    
    test_list = list(zip(class_ids.flatten(), conf.flatten(), bbox))
    if test_list[0][0] == 77:
        phone_box = test_list[0][2]
        #print(phone_box)
        print(conf)
        cv2.rectangle(frame, phone_box, (0, 255, 0), 2)
        cv2.putText(frame, "CELL PHONE", (phone_box[0] + 10, phone_box[1] + 30),
                           cv2.FONT_HERSHEY_PLAIN, 1, (0, 255, 0), 2)
        #indices = cv2.dnn.NMSBoxes(phone_box, conf, 0.5, 0.5)
#    for class_id in class_ids:
#         if class_id == 77:
#             indices = cv2.dnn.NMSBoxes(list(bbox), conf, 0.5, 0.5)
#             print(indices)
#             if class_id == 77:
#                 indices = cv2.dnn.NMSBoxes(list(bbox), conf, 0.5, 0.5)
#                 for i in indices:
#                     i = i[0]
#                     box = bbox[i]
#                     x, y, w, h = box[0], box[1], box[2], box[3]
#                     cv2.rectangle(frame, (x,y), (x+w, y+h), (0, 255, 0), 2)
#                     cv2.putText(frame, class_name[class_ids[i][0] - 1].upper(), (box[0] + 10, box[1] + 30),
#                                         cv2.FONT_HERSHEY_PLAIN, 1, (0, 255, 0), 2)
    
#     for class_id, confidence, box in zip(class_ids.flatten(), conf.flatten(), bbox):
#     #for class_id in class_ids:
#         if class_id == 77:
#             bbox = list(bbox)
#             conf = list(np.array(conf).reshape(1, -1)[0])
#             conf = list(map(float, conf))
            
#             indices = cv2.dnn.NMSBoxes(bbox, conf, 0.5, 0,5)

#         for i in indices:
#             i = i[0]
#             box = box[i]
#             x, y, w, h = box[0], box[1], box[2], box[3]
#             cv2.rectangle(frame, (x,y), (x+w, y+h), (0, 255, 0), 2)
#             cv2.putText(frame, class_name[class_ids[i][0] - 1].upper(), (box[0] + 10, box[1] + 30),
#                                 cv2.FONT_HERSHEY_PLAIN, 1, (0, 255, 0), 2)
    # put boxes and prediction if there is detection
#     if len(class_ids) != 0:
#         for class_id, confidence, box in zip(class_ids.flatten(), conf.flatten(), bbox):
#             bbox = list(bbox)
#             conf = list(np.array(conf).reshape(1, -1)[0])
#             conf = list(map(float, conf))
#             if class_id == 77:
#                 indices = cv2.dnn.NMSBoxes(bbox, conf, 0.5, 0,5)
#                 print(indices)
#             for i in indices:
#                 i = i[0]
#                 #box = box[i]
#                 #print(type(box))
#                 x, y, w, h = box[0], box[1], box[2], box[3]
#                 cv2.rectangle(frame, (x,y), (x+w, y+h), (0, 255, 0), 2)
#                 cv2.putText(frame, class_name[class_ids[i][0] - 1].upper(), (box[0] + 10, box[1] + 30),
#                                     cv2.FONT_HERSHEY_PLAIN, 1, (0, 255, 0), 2)
                
#                 cv2.rectangle(frame, box, (0, 255, 0), 2)
#                 cv2.putText(frame, class_name[class_id - 1].upper(), (box[0] + 10, box[1] + 30),
#                            cv2.FONT_HERSHEY_PLAIN, 1, (0, 255, 0), 2)

    cv2.imshow('test',frame)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
            break
cap.release()
cv2.destroyAllWindows()

[[0.7341821 ]
 [0.7035773 ]
 [0.45200562]
 [0.4046087 ]
 [0.3795413 ]
 [0.36315566]
 [0.36158043]
 [0.3465881 ]
 [0.33102328]
 [0.32427305]
 [0.30382133]
 [0.2862796 ]
 [0.27982223]
 [0.2679639 ]
 [0.2670919 ]
 [0.24584785]
 [0.24261343]
 [0.23997241]
 [0.23191   ]
 [0.23165609]
 [0.23098361]
 [0.22403178]
 [0.21676402]
 [0.20938976]
 [0.20842157]
 [0.20552853]
 [0.20472144]
 [0.19981088]
 [0.19169122]
 [0.18914919]
 [0.18712988]
 [0.18625896]
 [0.18470207]
 [0.18191382]
 [0.17850523]
 [0.17800038]
 [0.17536435]
 [0.17036898]
 [0.16944815]
 [0.1654022 ]
 [0.16047214]
 [0.15848856]
 [0.1563156 ]
 [0.1524183 ]
 [0.1513257 ]
 [0.15024942]
 [0.1446847 ]
 [0.14298631]
 [0.14024991]
 [0.13974617]
 [0.13971984]
 [0.13893549]
 [0.13743268]
 [0.13706298]
 [0.13695529]
 [0.13602445]
 [0.13548101]
 [0.13474864]
 [0.1345157 ]
 [0.13329896]
 [0.13284262]
 [0.13223103]
 [0.13002686]
 [0.12814929]
 [0.12802845]
 [0.12762988]
 [0.12696078]
 [0.12604018]
 [0.12408669]
 [0.12312643]
 [0.12212682]
 [0.12

[[0.78515637]
 [0.6777107 ]
 [0.43796417]
 [0.38163593]
 [0.37844154]
 [0.3777425 ]
 [0.37438652]
 [0.3718623 ]
 [0.35535294]
 [0.32246578]
 [0.30048347]
 [0.2981635 ]
 [0.29146567]
 [0.28865334]
 [0.2838445 ]
 [0.27153435]
 [0.26334482]
 [0.24988204]
 [0.24790443]
 [0.24650441]
 [0.23520845]
 [0.23074934]
 [0.20548585]
 [0.20308134]
 [0.20276971]
 [0.19550766]
 [0.18306561]
 [0.18227366]
 [0.17645946]
 [0.1665927 ]
 [0.16108641]
 [0.16009149]
 [0.15811282]
 [0.15614015]
 [0.15446903]
 [0.15362933]
 [0.15343238]
 [0.15281896]
 [0.15195937]
 [0.15037568]
 [0.15012696]
 [0.14855444]
 [0.14839914]
 [0.14558104]
 [0.14478557]
 [0.1434345 ]
 [0.14102988]
 [0.14079231]
 [0.1403942 ]
 [0.13918449]
 [0.13887668]
 [0.13849986]
 [0.13798048]
 [0.13577147]
 [0.13558272]
 [0.13323386]
 [0.1307935 ]
 [0.1306243 ]
 [0.12959912]
 [0.12942424]
 [0.12803586]
 [0.12773612]
 [0.12416945]
 [0.12227984]
 [0.1196683 ]
 [0.11792127]
 [0.11734782]
 [0.11658915]
 [0.11644818]
 [0.11531785]
 [0.11357495]
 [0.11

[[0.7614138 ]
 [0.68770766]
 [0.56782866]
 [0.41970968]
 [0.34056762]
 [0.33857328]
 [0.30377397]
 [0.27873802]
 [0.26177552]
 [0.25211778]
 [0.24450868]
 [0.22680192]
 [0.22071958]
 [0.21920654]
 [0.20930897]
 [0.20555663]
 [0.19588007]
 [0.19398151]
 [0.19265099]
 [0.1925589 ]
 [0.18712349]
 [0.17571075]
 [0.17072804]
 [0.16536573]
 [0.16466643]
 [0.16453542]
 [0.16311416]
 [0.1625402 ]
 [0.15184154]
 [0.15033844]
 [0.14899534]
 [0.1480851 ]
 [0.1471913 ]
 [0.1443062 ]
 [0.14387016]
 [0.1434709 ]
 [0.13966663]
 [0.13943067]
 [0.13517942]
 [0.13060127]
 [0.13020131]
 [0.12697388]
 [0.12688898]
 [0.1239825 ]
 [0.12287622]
 [0.12272856]
 [0.12272222]
 [0.12097449]
 [0.12075474]
 [0.11982297]
 [0.11971641]
 [0.11921902]
 [0.11883898]
 [0.11883559]
 [0.11812551]
 [0.11753187]
 [0.11611417]
 [0.11580209]
 [0.11487087]
 [0.11463907]
 [0.11421859]
 [0.11362182]
 [0.11277105]
 [0.11252946]
 [0.11161673]
 [0.11155386]
 [0.11085326]
 [0.10902682]
 [0.10902282]
 [0.10888859]
 [0.10883571]
 [0.10

[[0.6634537 ]
 [0.6391354 ]
 [0.45313033]
 [0.39732254]
 [0.38183063]
 [0.37185517]
 [0.36815488]
 [0.3644569 ]
 [0.33779147]
 [0.33722702]
 [0.30935737]
 [0.2954305 ]
 [0.28876215]
 [0.27655113]
 [0.2712193 ]
 [0.27017325]
 [0.26999182]
 [0.2684175 ]
 [0.26762697]
 [0.25328714]
 [0.24909039]
 [0.24895236]
 [0.24377908]
 [0.24331783]
 [0.24140646]
 [0.235032  ]
 [0.2318618 ]
 [0.23096983]
 [0.23038031]
 [0.21996197]
 [0.21586248]
 [0.2156205 ]
 [0.20885988]
 [0.2039823 ]
 [0.19703747]
 [0.19464286]
 [0.19002205]
 [0.18974033]
 [0.1881852 ]
 [0.18222155]
 [0.18208821]
 [0.17271705]
 [0.17266372]
 [0.1717135 ]
 [0.17017637]
 [0.16628632]
 [0.16556229]
 [0.16154394]
 [0.1599773 ]
 [0.15876485]
 [0.15433793]
 [0.15406524]
 [0.1538713 ]
 [0.15370151]
 [0.1536248 ]
 [0.15328637]
 [0.15326898]
 [0.1522012 ]
 [0.15172972]
 [0.15145376]
 [0.14950705]
 [0.14792074]
 [0.14640501]
 [0.14571112]
 [0.14520252]
 [0.14478688]
 [0.1445739 ]
 [0.14455166]
 [0.14343308]
 [0.14167687]
 [0.14046927]
 [0.13

[[0.74338746]
 [0.7318836 ]
 [0.37726867]
 [0.33438608]
 [0.3291296 ]
 [0.3019261 ]
 [0.29049656]
 [0.2673697 ]
 [0.2640213 ]
 [0.2529893 ]
 [0.25023234]
 [0.24752046]
 [0.22581251]
 [0.2252892 ]
 [0.22503547]
 [0.22353607]
 [0.22036639]
 [0.21400443]
 [0.20917584]
 [0.20745945]
 [0.19986899]
 [0.19629806]
 [0.19143173]
 [0.18991645]
 [0.18959814]
 [0.18820336]
 [0.18337071]
 [0.17822143]
 [0.17463222]
 [0.17398694]
 [0.16921556]
 [0.16719149]
 [0.16532893]
 [0.1650378 ]
 [0.1650298 ]
 [0.16499268]
 [0.16445144]
 [0.1642912 ]
 [0.16371934]
 [0.1634291 ]
 [0.1629636 ]
 [0.15766434]
 [0.15645161]
 [0.1557712 ]
 [0.1511743 ]
 [0.15110551]
 [0.15022217]
 [0.15004838]
 [0.14872572]
 [0.14753756]
 [0.14204523]
 [0.1413771 ]
 [0.14119534]
 [0.14026535]
 [0.13986124]
 [0.13984033]
 [0.13896699]
 [0.13891752]
 [0.13823694]
 [0.1378757 ]
 [0.13722235]
 [0.13654956]
 [0.13586012]
 [0.13512985]
 [0.13511641]
 [0.13461447]
 [0.13426977]
 [0.1338937 ]
 [0.13191678]
 [0.12977394]
 [0.1294992 ]
 [0.12

[[0.7627611 ]
 [0.7093023 ]
 [0.60260963]
 [0.47936097]
 [0.36129028]
 [0.33737516]
 [0.27027825]
 [0.26233467]
 [0.25946176]
 [0.2564936 ]
 [0.25595456]
 [0.23366539]
 [0.2296486 ]
 [0.22834495]
 [0.22155662]
 [0.21825618]
 [0.2129883 ]
 [0.20840049]
 [0.20179951]
 [0.20144911]
 [0.20030905]
 [0.1999971 ]
 [0.19841161]
 [0.19466004]
 [0.18634775]
 [0.18559705]
 [0.18406823]
 [0.18121761]
 [0.18025972]
 [0.17885748]
 [0.17628312]
 [0.17160602]
 [0.1707863 ]
 [0.170568  ]
 [0.17033017]
 [0.17021082]
 [0.16953182]
 [0.16755964]
 [0.16167364]
 [0.16047135]
 [0.16025035]
 [0.16003188]
 [0.15839407]
 [0.15508826]
 [0.15437935]
 [0.15413213]
 [0.15309419]
 [0.15114783]
 [0.14956212]
 [0.14276116]
 [0.14173244]
 [0.13886891]
 [0.13842419]
 [0.13748075]
 [0.13712595]
 [0.1341177 ]
 [0.13404167]
 [0.13381484]
 [0.13365363]
 [0.13340665]
 [0.13316469]
 [0.1325479 ]
 [0.13156258]
 [0.13090746]
 [0.12998292]
 [0.1288429 ]
 [0.12834089]
 [0.1277187 ]
 [0.12755302]
 [0.1270618 ]
 [0.12691127]
 [0.12

[[0.72711766]
 [0.7150336 ]
 [0.50277424]
 [0.41458833]
 [0.33290046]
 [0.31155956]
 [0.292456  ]
 [0.2864456 ]
 [0.28579733]
 [0.27408892]
 [0.25405446]
 [0.24206755]
 [0.23449595]
 [0.22142766]
 [0.21738297]
 [0.2166442 ]
 [0.2142884 ]
 [0.21295783]
 [0.21079358]
 [0.21016355]
 [0.19524519]
 [0.19143245]
 [0.18963756]
 [0.18510537]
 [0.1798959 ]
 [0.17648958]
 [0.17160468]
 [0.17018288]
 [0.16947687]
 [0.16763586]
 [0.16570328]
 [0.16445284]
 [0.16178222]
 [0.1604634 ]
 [0.15990362]
 [0.15656419]
 [0.15633135]
 [0.15552509]
 [0.15470141]
 [0.15393074]
 [0.15277232]
 [0.1523517 ]
 [0.15194371]
 [0.1470468 ]
 [0.14430885]
 [0.14424421]
 [0.14265928]
 [0.14138131]
 [0.14127553]
 [0.14120227]
 [0.14090016]
 [0.1404234 ]
 [0.1401987 ]
 [0.13883632]
 [0.1337394 ]
 [0.13055381]
 [0.12978892]
 [0.12867133]
 [0.12859271]
 [0.12825143]
 [0.12823099]
 [0.12790586]
 [0.12765265]
 [0.12725031]
 [0.12552854]
 [0.12442323]
 [0.12297899]
 [0.12271513]
 [0.12230995]
 [0.12210987]
 [0.12121788]
 [0.12

[[0.7762598 ]
 [0.72583985]
 [0.30990037]
 [0.28088233]
 [0.25414568]
 [0.24928296]
 [0.24472262]
 [0.23994684]
 [0.22995713]
 [0.22356696]
 [0.21795802]
 [0.21113497]
 [0.20158687]
 [0.20099002]
 [0.19720045]
 [0.19657148]
 [0.1947767 ]
 [0.19174635]
 [0.18911093]
 [0.18629357]
 [0.18502836]
 [0.18292034]
 [0.18204102]
 [0.1812269 ]
 [0.17814606]
 [0.1761103 ]
 [0.17507105]
 [0.1636769 ]
 [0.15760696]
 [0.1556323 ]
 [0.15308112]
 [0.15087263]
 [0.15026383]
 [0.14764628]
 [0.14690544]
 [0.14670828]
 [0.14348395]
 [0.14274481]
 [0.14241035]
 [0.13676181]
 [0.13662595]
 [0.13622218]
 [0.1357918 ]
 [0.13482866]
 [0.13448517]
 [0.13191628]
 [0.13139941]
 [0.12956755]
 [0.12926385]
 [0.12875874]
 [0.12867749]
 [0.12854537]
 [0.12828915]
 [0.12761836]
 [0.12658624]
 [0.12601085]
 [0.12573515]
 [0.12522048]
 [0.12410688]
 [0.12346062]
 [0.12200836]
 [0.12181834]
 [0.12168294]
 [0.12087766]
 [0.11820396]
 [0.11752866]
 [0.11689594]
 [0.11655426]
 [0.11580326]
 [0.11499674]
 [0.11442401]
 [0.11

[[0.7450056 ]
 [0.7271467 ]
 [0.31352755]
 [0.28753284]
 [0.26647872]
 [0.2559825 ]
 [0.24520795]
 [0.22781293]
 [0.22727193]
 [0.2269037 ]
 [0.22153606]
 [0.22068112]
 [0.21658005]
 [0.2158622 ]
 [0.2145786 ]
 [0.20755948]
 [0.20232031]
 [0.20088159]
 [0.19962901]
 [0.19552998]
 [0.19506676]
 [0.19414191]
 [0.19052081]
 [0.18914086]
 [0.18837117]
 [0.18624541]
 [0.1856611 ]
 [0.18397133]
 [0.18391953]
 [0.18367875]
 [0.18352024]
 [0.17962684]
 [0.17800975]
 [0.17770734]
 [0.17357779]
 [0.16686706]
 [0.16632228]
 [0.16437013]
 [0.16197231]
 [0.15963078]
 [0.15883848]
 [0.15603179]
 [0.15450594]
 [0.15286556]
 [0.1525143 ]
 [0.15148798]
 [0.14845873]
 [0.14783232]
 [0.14751759]
 [0.14590785]
 [0.14492568]
 [0.14459467]
 [0.14359488]
 [0.14102748]
 [0.14084278]
 [0.13998428]
 [0.13844463]
 [0.13716713]
 [0.13687573]
 [0.13644823]
 [0.13608502]
 [0.13428096]
 [0.13314635]
 [0.13152699]
 [0.12762868]
 [0.12618686]
 [0.12453255]
 [0.12420346]
 [0.12220539]
 [0.11842497]
 [0.11832549]
 [0.11

[[0.73713917]
 [0.7147957 ]
 [0.41057503]
 [0.37906638]
 [0.3613473 ]
 [0.3455491 ]
 [0.33212638]
 [0.31718695]
 [0.30522865]
 [0.24693415]
 [0.23318276]
 [0.2323117 ]
 [0.23056602]
 [0.22285594]
 [0.22102273]
 [0.22041088]
 [0.21022466]
 [0.20760791]
 [0.20079486]
 [0.20047319]
 [0.19941491]
 [0.19767588]
 [0.19400007]
 [0.18679446]
 [0.18595114]
 [0.1840777 ]
 [0.18366103]
 [0.18212245]
 [0.18033163]
 [0.178884  ]
 [0.17625159]
 [0.17567424]
 [0.17418812]
 [0.17405528]
 [0.17384008]
 [0.17339039]
 [0.17181113]
 [0.17114271]
 [0.16997977]
 [0.16994545]
 [0.16769919]
 [0.16740353]
 [0.16450764]
 [0.16339594]
 [0.16174884]
 [0.16156559]
 [0.15925223]
 [0.15763104]
 [0.15758985]
 [0.15725456]
 [0.1557623 ]
 [0.15442152]
 [0.15067935]
 [0.15058891]
 [0.15012087]
 [0.14986531]
 [0.14840779]
 [0.14676186]
 [0.14373498]
 [0.14351222]
 [0.138926  ]
 [0.13421232]
 [0.13381918]
 [0.13373153]
 [0.13341121]
 [0.13147561]
 [0.12924308]
 [0.12832262]
 [0.12827103]
 [0.12721594]
 [0.1266601 ]
 [0.12

[[0.72780824]
 [0.72269404]
 [0.35357565]
 [0.3446494 ]
 [0.29299444]
 [0.2877319 ]
 [0.28682327]
 [0.2828773 ]
 [0.28124076]
 [0.26629382]
 [0.23825887]
 [0.23079617]
 [0.22305869]
 [0.22079027]
 [0.21776403]
 [0.21629177]
 [0.21608312]
 [0.21419246]
 [0.21094671]
 [0.20828201]
 [0.20613623]
 [0.20491102]
 [0.20405194]
 [0.19909705]
 [0.19896677]
 [0.19466905]
 [0.18813168]
 [0.18654892]
 [0.18632518]
 [0.17630473]
 [0.17509978]
 [0.17496914]
 [0.17430364]
 [0.17324282]
 [0.17263745]
 [0.17109267]
 [0.16983554]
 [0.16674343]
 [0.16418265]
 [0.16281962]
 [0.1583244 ]
 [0.15794101]
 [0.1563951 ]
 [0.15418044]
 [0.15043464]
 [0.1500253 ]
 [0.14743946]
 [0.14720209]
 [0.14572608]
 [0.14479774]
 [0.14351095]
 [0.14329983]
 [0.14329967]
 [0.14178272]
 [0.13827536]
 [0.1377918 ]
 [0.1375556 ]
 [0.13600165]
 [0.13473254]
 [0.1342159 ]
 [0.13391975]
 [0.1336945 ]
 [0.1329641 ]
 [0.13272192]
 [0.1326702 ]
 [0.13239118]
 [0.13161626]
 [0.13133617]
 [0.13004373]
 [0.12986407]
 [0.1290043 ]
 [0.12

[[0.7729866 ]
 [0.7432135 ]
 [0.33651724]
 [0.3352256 ]
 [0.3127219 ]
 [0.30367625]
 [0.29486537]
 [0.2773084 ]
 [0.25811645]
 [0.25214353]
 [0.25120705]
 [0.24089266]
 [0.22278427]
 [0.22230752]
 [0.2207423 ]
 [0.21981698]
 [0.21097477]
 [0.21072589]
 [0.21044   ]
 [0.20656726]
 [0.18598267]
 [0.18396576]
 [0.1838086 ]
 [0.17787312]
 [0.1775676 ]
 [0.17355956]
 [0.17160131]
 [0.17156763]
 [0.16900845]
 [0.16893873]
 [0.16801375]
 [0.16491205]
 [0.16465108]
 [0.1643354 ]
 [0.16077548]
 [0.1599899 ]
 [0.15974422]
 [0.15616333]
 [0.154848  ]
 [0.14871338]
 [0.14831156]
 [0.14823796]
 [0.14748545]
 [0.14731623]
 [0.14725596]
 [0.14687161]
 [0.14613354]
 [0.14525412]
 [0.14257748]
 [0.14187348]
 [0.14073823]
 [0.13957292]
 [0.13954203]
 [0.13844128]
 [0.13770759]
 [0.13762167]
 [0.13736284]
 [0.13666138]
 [0.13665035]
 [0.1337206 ]
 [0.13289183]
 [0.13278   ]
 [0.1325179 ]
 [0.12815118]
 [0.12685907]
 [0.1261646 ]
 [0.1259257 ]
 [0.1246601 ]
 [0.12435529]
 [0.12419563]
 [0.12295907]
 [0.12

[[0.80900705]
 [0.73143697]
 [0.29525313]
 [0.27995685]
 [0.27455807]
 [0.2695844 ]
 [0.2585659 ]
 [0.25850624]
 [0.22825201]
 [0.22810027]
 [0.21664014]
 [0.20816977]
 [0.20173885]
 [0.20059207]
 [0.20037937]
 [0.19986568]
 [0.19867975]
 [0.19244003]
 [0.19067374]
 [0.18963566]
 [0.18846695]
 [0.18693283]
 [0.18612902]
 [0.18018267]
 [0.17975314]
 [0.17609629]
 [0.17452218]
 [0.17182799]
 [0.16824265]
 [0.16794102]
 [0.1673138 ]
 [0.15892537]
 [0.15836257]
 [0.15665588]
 [0.15497512]
 [0.15451403]
 [0.152424  ]
 [0.1502609 ]
 [0.14914326]
 [0.14692773]
 [0.14603512]
 [0.14576422]
 [0.14570409]
 [0.1454178 ]
 [0.14094715]
 [0.13980052]
 [0.13770132]
 [0.1376995 ]
 [0.1339809 ]
 [0.13277915]
 [0.13166593]
 [0.13120997]
 [0.13024879]
 [0.12888172]
 [0.12852794]
 [0.12715982]
 [0.12706886]
 [0.12697247]
 [0.12608278]
 [0.12567657]
 [0.12406339]
 [0.12376749]
 [0.1234585 ]
 [0.12006361]
 [0.11965822]
 [0.11962194]
 [0.11907042]
 [0.11880189]
 [0.1173825 ]
 [0.1171952 ]
 [0.11663997]
 [0.11

[[0.8212547 ]
 [0.7340468 ]
 [0.32853076]
 [0.29111308]
 [0.2791134 ]
 [0.2687728 ]
 [0.2601058 ]
 [0.24283734]
 [0.24264932]
 [0.24223876]
 [0.24165192]
 [0.22327852]
 [0.22168429]
 [0.22155382]
 [0.21495126]
 [0.20739749]
 [0.20511572]
 [0.20082316]
 [0.19972235]
 [0.19049384]
 [0.19028752]
 [0.18962964]
 [0.18847378]
 [0.18720695]
 [0.18320774]
 [0.18282497]
 [0.18210818]
 [0.17521948]
 [0.17397833]
 [0.17397445]
 [0.1734892 ]
 [0.17233226]
 [0.17120682]
 [0.16544965]
 [0.16502273]
 [0.1641383 ]
 [0.16393507]
 [0.16385078]
 [0.1618421 ]
 [0.15771239]
 [0.15649654]
 [0.15363932]
 [0.1536218 ]
 [0.15349823]
 [0.15329067]
 [0.15082514]
 [0.15015909]
 [0.14872825]
 [0.14681995]
 [0.14504892]
 [0.14440052]
 [0.14425421]
 [0.14398171]
 [0.14349969]
 [0.14345707]
 [0.14327344]
 [0.14025944]
 [0.13983196]
 [0.138822  ]
 [0.1369963 ]
 [0.13489528]
 [0.1346952 ]
 [0.1330692 ]
 [0.13281783]
 [0.13274242]
 [0.13266811]
 [0.13021696]
 [0.12949008]
 [0.1284298 ]
 [0.12599246]
 [0.12595536]
 [0.12

[[0.8161738 ]
 [0.7369147 ]
 [0.29753962]
 [0.295483  ]
 [0.2738445 ]
 [0.27016392]
 [0.2592723 ]
 [0.25771603]
 [0.24879998]
 [0.24243784]
 [0.24043153]
 [0.23192441]
 [0.22874495]
 [0.22080928]
 [0.21239503]
 [0.20924619]
 [0.20473538]
 [0.20070553]
 [0.19837885]
 [0.1953608 ]
 [0.19181725]
 [0.1907415 ]
 [0.19053732]
 [0.19015151]
 [0.18764211]
 [0.18106899]
 [0.18069826]
 [0.17809086]
 [0.16770108]
 [0.16441998]
 [0.1632826 ]
 [0.1566782 ]
 [0.15651752]
 [0.1564619 ]
 [0.1563502 ]
 [0.1560185 ]
 [0.15427954]
 [0.15405788]
 [0.15284725]
 [0.15248875]
 [0.15241536]
 [0.15069251]
 [0.14731234]
 [0.1465641 ]
 [0.1460784 ]
 [0.14541765]
 [0.14489867]
 [0.14408119]
 [0.14405459]
 [0.14346452]
 [0.14159071]
 [0.1412245 ]
 [0.14068665]
 [0.13616757]
 [0.13277377]
 [0.1321662 ]
 [0.13091767]
 [0.13063504]
 [0.1300114 ]
 [0.12827127]
 [0.12673876]
 [0.12633207]
 [0.12605636]
 [0.12601694]
 [0.12512814]
 [0.12476907]
 [0.12442798]
 [0.12411902]
 [0.12356488]
 [0.12351041]
 [0.12315232]
 [0.12

[[0.8085458 ]
 [0.73021764]
 [0.28917614]
 [0.27009183]
 [0.269827  ]
 [0.2638849 ]
 [0.26024127]
 [0.25635988]
 [0.2530819 ]
 [0.25088692]
 [0.24626718]
 [0.23782022]
 [0.2358323 ]
 [0.23095807]
 [0.2308    ]
 [0.22771883]
 [0.21950173]
 [0.21897267]
 [0.21409665]
 [0.2097573 ]
 [0.20309602]
 [0.19892882]
 [0.1966202 ]
 [0.19464985]
 [0.19390568]
 [0.19236441]
 [0.18759581]
 [0.17935286]
 [0.17597052]
 [0.17433968]
 [0.17323343]
 [0.17088978]
 [0.16667564]
 [0.16178931]
 [0.16175237]
 [0.16131055]
 [0.1611831 ]
 [0.16092385]
 [0.15795112]
 [0.15403046]
 [0.15307307]
 [0.15168525]
 [0.15144934]
 [0.1512781 ]
 [0.15006094]
 [0.14954841]
 [0.14901268]
 [0.14719725]
 [0.1425243 ]
 [0.14079213]
 [0.13999793]
 [0.13850307]
 [0.13760881]
 [0.13615663]
 [0.13522978]
 [0.13400993]
 [0.1335762 ]
 [0.13326387]
 [0.13090153]
 [0.13011898]
 [0.1299924 ]
 [0.12968855]
 [0.12699102]
 [0.12687095]
 [0.12595522]
 [0.12555595]
 [0.12482917]
 [0.12469945]
 [0.12454219]
 [0.12360983]
 [0.1232621 ]
 [0.12

[[0.80276304]
 [0.7392384 ]
 [0.28778994]
 [0.28700098]
 [0.2826371 ]
 [0.26267788]
 [0.25263095]
 [0.2434373 ]
 [0.23141561]
 [0.22921884]
 [0.21545506]
 [0.20848045]
 [0.2083611 ]
 [0.20346928]
 [0.20107517]
 [0.20042196]
 [0.1992548 ]
 [0.19909993]
 [0.18819228]
 [0.1840274 ]
 [0.18261951]
 [0.18122801]
 [0.18088457]
 [0.17655417]
 [0.17322642]
 [0.17249054]
 [0.16938601]
 [0.16858573]
 [0.16766691]
 [0.16549948]
 [0.16303039]
 [0.16244105]
 [0.16091551]
 [0.15924881]
 [0.15727499]
 [0.15706205]
 [0.15692739]
 [0.1554555 ]
 [0.15134782]
 [0.15075961]
 [0.14945836]
 [0.1474024 ]
 [0.14630532]
 [0.1446496 ]
 [0.14254943]
 [0.14072356]
 [0.13695712]
 [0.13694604]
 [0.13628203]
 [0.13538955]
 [0.13504262]
 [0.13493566]
 [0.13111393]
 [0.13053776]
 [0.1304526 ]
 [0.13027085]
 [0.12777315]
 [0.12769398]
 [0.12754045]
 [0.12439854]
 [0.12287322]
 [0.12247791]
 [0.12181386]
 [0.12176411]
 [0.11970396]
 [0.11917865]
 [0.11666206]
 [0.11545953]
 [0.11431942]
 [0.11395462]
 [0.11390875]
 [0.11

[[0.8072418 ]
 [0.7256941 ]
 [0.32247102]
 [0.2654417 ]
 [0.26430315]
 [0.26354983]
 [0.25184587]
 [0.2452226 ]
 [0.22788286]
 [0.22016142]
 [0.21599224]
 [0.21527244]
 [0.21525988]
 [0.21345177]
 [0.21242516]
 [0.20862421]
 [0.20685081]
 [0.20041686]
 [0.19829158]
 [0.19102329]
 [0.19078049]
 [0.18839398]
 [0.18815677]
 [0.18370752]
 [0.17967163]
 [0.1796115 ]
 [0.17627512]
 [0.1755094 ]
 [0.17071055]
 [0.17019597]
 [0.16593346]
 [0.16350615]
 [0.16328382]
 [0.160577  ]
 [0.15837969]
 [0.15800893]
 [0.15752068]
 [0.15705195]
 [0.15609828]
 [0.14912966]
 [0.14810292]
 [0.14774527]
 [0.14624724]
 [0.14434206]
 [0.1439227 ]
 [0.14379326]
 [0.14239772]
 [0.14152682]
 [0.14138179]
 [0.14004937]
 [0.13827568]
 [0.13749795]
 [0.1374273 ]
 [0.13419634]
 [0.13137746]
 [0.13088945]
 [0.1298649 ]
 [0.12813483]
 [0.12705082]
 [0.12588577]
 [0.12463293]
 [0.1242535 ]
 [0.12201481]
 [0.12164778]
 [0.11958947]
 [0.11933263]
 [0.11871561]
 [0.11827769]
 [0.11716603]
 [0.11687379]
 [0.116195  ]
 [0.11

[[0.79068214]
 [0.73452497]
 [0.31380895]
 [0.29897377]
 [0.29346773]
 [0.27256557]
 [0.25492904]
 [0.25400195]
 [0.23626012]
 [0.22272421]
 [0.22151451]
 [0.20800617]
 [0.20360298]
 [0.20343417]
 [0.1975869 ]
 [0.19208702]
 [0.1919802 ]
 [0.19111356]
 [0.18733688]
 [0.1833823 ]
 [0.18316287]
 [0.18257497]
 [0.18165289]
 [0.171431  ]
 [0.17135255]
 [0.17117189]
 [0.16883683]
 [0.16793263]
 [0.16401182]
 [0.16273913]
 [0.16142944]
 [0.15843172]
 [0.15795396]
 [0.15672445]
 [0.15520222]
 [0.15435176]
 [0.15157591]
 [0.15070605]
 [0.14829643]
 [0.14817794]
 [0.14621662]
 [0.1428551 ]
 [0.14167435]
 [0.14129385]
 [0.13976686]
 [0.13956083]
 [0.13863997]
 [0.13709316]
 [0.13708967]
 [0.13606939]
 [0.13575752]
 [0.13571048]
 [0.13515066]
 [0.13455056]
 [0.13245213]
 [0.13051076]
 [0.12888983]
 [0.12774971]
 [0.12644574]
 [0.12505156]
 [0.12387926]
 [0.12364367]
 [0.12250942]
 [0.12210171]
 [0.12088064]
 [0.11994913]
 [0.11808078]
 [0.11654288]
 [0.11608725]
 [0.11524296]
 [0.11451644]
 [0.11

[[0.78899616]
 [0.7207959 ]
 [0.28871948]
 [0.2722272 ]
 [0.27051884]
 [0.26963085]
 [0.26801375]
 [0.26663527]
 [0.24485105]
 [0.22699901]
 [0.2220131 ]
 [0.21789972]
 [0.21300286]
 [0.21135034]
 [0.20952101]
 [0.20764826]
 [0.2020489 ]
 [0.19881842]
 [0.19774286]
 [0.19750506]
 [0.19640577]
 [0.1948243 ]
 [0.19113107]
 [0.18846257]
 [0.18602143]
 [0.18538208]
 [0.18316141]
 [0.18312828]
 [0.18227796]
 [0.17728773]
 [0.17373836]
 [0.17360684]
 [0.17045291]
 [0.16995029]
 [0.1677488 ]
 [0.16729143]
 [0.16442432]
 [0.16438231]
 [0.16031383]
 [0.15969136]
 [0.15894863]
 [0.15694001]
 [0.15563373]
 [0.15470096]
 [0.15460864]
 [0.15402143]
 [0.15192577]
 [0.15140034]
 [0.1494683 ]
 [0.14380214]
 [0.14124899]
 [0.1387197 ]
 [0.13861683]
 [0.1382215 ]
 [0.13517627]
 [0.13515948]
 [0.13476934]
 [0.13438125]
 [0.13140944]
 [0.1303607 ]
 [0.1281753 ]
 [0.12660044]
 [0.12497679]
 [0.12482826]
 [0.1247974 ]
 [0.12451433]
 [0.12303611]
 [0.12093497]
 [0.11861096]
 [0.11814726]
 [0.11619356]
 [0.11

[[0.7324954 ]
 [0.70084083]
 [0.49070868]
 [0.41831827]
 [0.3847071 ]
 [0.33050212]
 [0.3291463 ]
 [0.31544322]
 [0.3016926 ]
 [0.28935355]
 [0.28208947]
 [0.2575542 ]
 [0.23641938]
 [0.23241715]
 [0.20502605]
 [0.19910744]
 [0.19433984]
 [0.19036306]
 [0.18637533]
 [0.18256176]
 [0.1777061 ]
 [0.17262256]
 [0.1700428 ]
 [0.16901849]
 [0.16895777]
 [0.1669171 ]
 [0.16672227]
 [0.16577676]
 [0.16555929]
 [0.16304912]
 [0.16293123]
 [0.15865281]
 [0.15669115]
 [0.15592444]
 [0.15156937]
 [0.15143678]
 [0.15069038]
 [0.1501462 ]
 [0.14952143]
 [0.14801909]
 [0.14763539]
 [0.14691456]
 [0.14667933]
 [0.1446311 ]
 [0.14338157]
 [0.14253888]
 [0.14212584]
 [0.14090396]
 [0.13863301]
 [0.13530535]
 [0.13510396]
 [0.13419224]
 [0.13405512]
 [0.13334417]
 [0.13307978]
 [0.1315164 ]
 [0.13084751]
 [0.13069145]
 [0.13042769]
 [0.1302477 ]
 [0.12671171]
 [0.12579693]
 [0.12477902]
 [0.12366572]
 [0.12108883]
 [0.11969855]
 [0.11881916]
 [0.11875142]
 [0.11822577]
 [0.11768666]
 [0.11671719]
 [0.11

[[0.7374064 ]
 [0.71914953]
 [0.49456453]
 [0.4267551 ]
 [0.41942555]
 [0.37529966]
 [0.37353012]
 [0.3468037 ]
 [0.32292542]
 [0.27040204]
 [0.25466254]
 [0.22343309]
 [0.21809874]
 [0.21697228]
 [0.21197106]
 [0.20954081]
 [0.20706438]
 [0.20567645]
 [0.20060454]
 [0.18917732]
 [0.1840191 ]
 [0.16886361]
 [0.16798002]
 [0.16496783]
 [0.16178745]
 [0.1609468 ]
 [0.16030623]
 [0.15730575]
 [0.15091752]
 [0.15052775]
 [0.14909475]
 [0.14498897]
 [0.14423235]
 [0.14232424]
 [0.14022306]
 [0.13741663]
 [0.13715482]
 [0.1369243 ]
 [0.13430697]
 [0.13394065]
 [0.13309939]
 [0.13148256]
 [0.12931931]
 [0.12710975]
 [0.12675631]
 [0.12632947]
 [0.12620589]
 [0.12488495]
 [0.12466494]
 [0.12462671]
 [0.12311108]
 [0.1226238 ]
 [0.1222714 ]
 [0.12164363]
 [0.12139625]
 [0.12087854]
 [0.1204423 ]
 [0.11971197]
 [0.11903508]
 [0.11828044]
 [0.11728941]
 [0.11673722]
 [0.1166884 ]
 [0.11630971]
 [0.1162899 ]
 [0.11518517]
 [0.11346162]
 [0.11145116]
 [0.11106508]
 [0.11101019]
 [0.11031891]
 [0.11

[[0.7397279 ]
 [0.72100353]
 [0.48849705]
 [0.48593172]
 [0.4389146 ]
 [0.4252387 ]
 [0.34408778]
 [0.31966007]
 [0.30269033]
 [0.28648528]
 [0.28218693]
 [0.28056753]
 [0.27714652]
 [0.26347053]
 [0.24710879]
 [0.24314132]
 [0.24046963]
 [0.2197281 ]
 [0.20581234]
 [0.20237884]
 [0.1998373 ]
 [0.19768727]
 [0.19540624]
 [0.18581203]
 [0.18419999]
 [0.1820117 ]
 [0.18073887]
 [0.17844445]
 [0.17836173]
 [0.17558001]
 [0.17449546]
 [0.17164147]
 [0.17111394]
 [0.16988143]
 [0.16788828]
 [0.16559984]
 [0.1592103 ]
 [0.15783562]
 [0.15539415]
 [0.15332833]
 [0.15044807]
 [0.15031962]
 [0.14977244]
 [0.14477468]
 [0.14435229]
 [0.14349523]
 [0.14130981]
 [0.14077644]
 [0.140267  ]
 [0.13951582]
 [0.13782683]
 [0.13763256]
 [0.13596018]
 [0.13588816]
 [0.13460511]
 [0.13443981]
 [0.13320655]
 [0.13083796]
 [0.12982765]
 [0.12918667]
 [0.12898797]
 [0.12836425]
 [0.12775207]
 [0.1264183 ]
 [0.12630236]
 [0.12609375]
 [0.12586528]
 [0.12490962]
 [0.12442267]
 [0.12429485]
 [0.12396228]
 [0.12

[[0.74000067]
 [0.7140593 ]
 [0.4811713 ]
 [0.4468016 ]
 [0.40170717]
 [0.37621182]
 [0.3741297 ]
 [0.3463222 ]
 [0.33490115]
 [0.29382402]
 [0.28157088]
 [0.25354913]
 [0.24413101]
 [0.2378718 ]
 [0.22609867]
 [0.21614031]
 [0.21598405]
 [0.2064358 ]
 [0.19945313]
 [0.1989628 ]
 [0.1986838 ]
 [0.19656028]
 [0.19017375]
 [0.18958668]
 [0.18884236]
 [0.18633969]
 [0.18546207]
 [0.18526283]
 [0.18524893]
 [0.18216391]
 [0.18191147]
 [0.18189117]
 [0.18136407]
 [0.17926948]
 [0.17670947]
 [0.17619832]
 [0.17613637]
 [0.1731967 ]
 [0.16772816]
 [0.16483915]
 [0.16409162]
 [0.1630085 ]
 [0.16255017]
 [0.16054879]
 [0.15735339]
 [0.15661164]
 [0.15379746]
 [0.15164328]
 [0.15054217]
 [0.14924121]
 [0.14879161]
 [0.14786653]
 [0.14726514]
 [0.14702092]
 [0.14634554]
 [0.14404352]
 [0.14324386]
 [0.14297542]
 [0.14025366]
 [0.13826461]
 [0.13663457]
 [0.1352891 ]
 [0.13460195]
 [0.13384232]
 [0.13371012]
 [0.13293755]
 [0.13269976]
 [0.13167858]
 [0.13144968]
 [0.13036327]
 [0.13034177]
 [0.13

[[0.72719884]
 [0.71263975]
 [0.56106204]
 [0.47288087]
 [0.42801297]
 [0.36771342]
 [0.35984072]
 [0.33497125]
 [0.32930678]
 [0.28889441]
 [0.28615358]
 [0.2594865 ]
 [0.25224718]
 [0.2329084 ]
 [0.21654503]
 [0.20681046]
 [0.20651944]
 [0.2063892 ]
 [0.20439479]
 [0.20418775]
 [0.2037156 ]
 [0.20237987]
 [0.19901255]
 [0.19000351]
 [0.18831865]
 [0.18539295]
 [0.18462014]
 [0.18340208]
 [0.18218982]
 [0.18063805]
 [0.17823984]
 [0.17682609]
 [0.17302097]
 [0.17212461]
 [0.17050318]
 [0.16660066]
 [0.16380192]
 [0.16359088]
 [0.16127494]
 [0.1600983 ]
 [0.15908723]
 [0.15564981]
 [0.15470365]
 [0.15316847]
 [0.1530206 ]
 [0.15255834]
 [0.14884768]
 [0.14775063]
 [0.14660794]
 [0.14632551]
 [0.14577489]
 [0.14446497]
 [0.14432915]
 [0.1428794 ]
 [0.1419017 ]
 [0.14169358]
 [0.14123966]
 [0.14092222]
 [0.14059524]
 [0.14043176]
 [0.1391125 ]
 [0.1366294 ]
 [0.13648397]
 [0.13615054]
 [0.13541874]
 [0.13453732]
 [0.13427597]
 [0.13361779]
 [0.13273466]
 [0.132637  ]
 [0.13136023]
 [0.13

[[0.71751004]
 [0.70051277]
 [0.52615565]
 [0.48664254]
 [0.41018716]
 [0.34840932]
 [0.3148344 ]
 [0.29805875]
 [0.28025335]
 [0.26772174]
 [0.25770167]
 [0.24087138]
 [0.23882663]
 [0.23061204]
 [0.22987992]
 [0.21083663]
 [0.20289917]
 [0.19192086]
 [0.18670173]
 [0.18464619]
 [0.18351625]
 [0.18085097]
 [0.18076918]
 [0.18040338]
 [0.1799533 ]
 [0.17932282]
 [0.17833142]
 [0.17819823]
 [0.17762886]
 [0.17552455]
 [0.17213425]
 [0.17065749]
 [0.16906841]
 [0.16824828]
 [0.16747683]
 [0.1660744 ]
 [0.16161256]
 [0.16070594]
 [0.16039881]
 [0.1595193 ]
 [0.15774764]
 [0.15657833]
 [0.15568349]
 [0.15406553]
 [0.15229417]
 [0.1504595 ]
 [0.1499325 ]
 [0.14963911]
 [0.14719844]
 [0.1450114 ]
 [0.1444063 ]
 [0.14388515]
 [0.14366397]
 [0.14359254]
 [0.14282843]
 [0.14281923]
 [0.14175446]
 [0.14173505]
 [0.1407016 ]
 [0.140319  ]
 [0.13672397]
 [0.13572633]
 [0.13503957]
 [0.13315813]
 [0.13265644]
 [0.1310945 ]
 [0.13049142]
 [0.12983918]
 [0.12907526]
 [0.12905917]
 [0.12889633]
 [0.12

[[0.7426448 ]
 [0.7024296 ]
 [0.5720745 ]
 [0.5305753 ]
 [0.46489686]
 [0.42355394]
 [0.3971262 ]
 [0.38212618]
 [0.37812525]
 [0.32771742]
 [0.31140128]
 [0.31094554]
 [0.2805976 ]
 [0.27640516]
 [0.27514476]
 [0.27451122]
 [0.26369384]
 [0.22673336]
 [0.22101074]
 [0.21921685]
 [0.21172847]
 [0.20394202]
 [0.20139651]
 [0.19799869]
 [0.19729494]
 [0.18822443]
 [0.1874609 ]
 [0.1871331 ]
 [0.18707755]
 [0.1856055 ]
 [0.18505462]
 [0.1819442 ]
 [0.17829476]
 [0.17510661]
 [0.17422806]
 [0.17362504]
 [0.1735902 ]
 [0.17057984]
 [0.17040057]
 [0.16954951]
 [0.16681826]
 [0.16146082]
 [0.15831016]
 [0.15655014]
 [0.15573329]
 [0.15511268]
 [0.15476304]
 [0.15279382]
 [0.1513274 ]
 [0.15132275]
 [0.15097001]
 [0.15041773]
 [0.14777526]
 [0.145089  ]
 [0.14394899]
 [0.14356628]
 [0.14245705]
 [0.1413479 ]
 [0.14117892]
 [0.14043024]
 [0.13612819]
 [0.13566734]
 [0.13484594]
 [0.13463771]
 [0.1343531 ]
 [0.13343129]
 [0.13249914]
 [0.13174261]
 [0.1312972 ]
 [0.13050091]
 [0.12940602]
 [0.12

[[0.6772706 ]
 [0.6719686 ]
 [0.49571335]
 [0.42791432]
 [0.42064977]
 [0.41420668]
 [0.3505361 ]
 [0.33597893]
 [0.30815727]
 [0.2991612 ]
 [0.28997907]
 [0.26728314]
 [0.2602624 ]
 [0.24617979]
 [0.24368396]
 [0.23786484]
 [0.23489054]
 [0.23431551]
 [0.23398246]
 [0.22679156]
 [0.22366796]
 [0.2214711 ]
 [0.22077183]
 [0.21955615]
 [0.21707387]
 [0.21638548]
 [0.2112138 ]
 [0.20310771]
 [0.20242542]
 [0.20241018]
 [0.19669278]
 [0.19663697]
 [0.19266297]
 [0.18874891]
 [0.18788964]
 [0.18537012]
 [0.18414354]
 [0.1774642 ]
 [0.17544998]
 [0.17209569]
 [0.1715182 ]
 [0.16878355]
 [0.16856995]
 [0.16475882]
 [0.16472246]
 [0.16457969]
 [0.16002156]
 [0.15993705]
 [0.15931247]
 [0.15784626]
 [0.15656537]
 [0.15423168]
 [0.1517079 ]
 [0.15163776]
 [0.15068194]
 [0.1500372 ]
 [0.14941314]
 [0.14718015]
 [0.14406005]
 [0.14394313]
 [0.14108025]
 [0.1407301 ]
 [0.14040852]
 [0.14033009]
 [0.13869703]
 [0.1368221 ]
 [0.13663481]
 [0.13454697]
 [0.13225128]
 [0.12796322]
 [0.12743701]
 [0.12

[[0.70023024]
 [0.6792071 ]
 [0.4776717 ]
 [0.42127758]
 [0.3931911 ]
 [0.38984746]
 [0.35667512]
 [0.3364672 ]
 [0.32978028]
 [0.31865516]
 [0.2809781 ]
 [0.2756496 ]
 [0.27033764]
 [0.26998213]
 [0.2612314 ]
 [0.24098742]
 [0.23118874]
 [0.22857025]
 [0.2264563 ]
 [0.22219533]
 [0.21005486]
 [0.18865868]
 [0.18814118]
 [0.1878129 ]
 [0.18360949]
 [0.18079062]
 [0.174022  ]
 [0.16708192]
 [0.16529329]
 [0.16289996]
 [0.15966617]
 [0.15523103]
 [0.15002728]
 [0.14998396]
 [0.14973012]
 [0.14857206]
 [0.14840811]
 [0.14697923]
 [0.14267462]
 [0.14097072]
 [0.1371924 ]
 [0.13627297]
 [0.13532093]
 [0.13415118]
 [0.13391286]
 [0.13207592]
 [0.13061021]
 [0.13034551]
 [0.12961811]
 [0.1288094 ]
 [0.12861425]
 [0.12820587]
 [0.12631097]
 [0.12534754]
 [0.12438453]
 [0.12359139]
 [0.12348662]
 [0.12318569]
 [0.12214338]
 [0.12125254]
 [0.12124442]
 [0.12121361]
 [0.12089858]
 [0.11947841]
 [0.1188671 ]
 [0.11728589]
 [0.11706732]
 [0.1169099 ]
 [0.11570469]
 [0.11477079]
 [0.11417244]
 [0.11

[[0.6799256 ]
 [0.6755489 ]
 [0.35566834]
 [0.33404115]
 [0.30826116]
 [0.28016895]
 [0.27110663]
 [0.25400743]
 [0.24307692]
 [0.23605199]
 [0.23465738]
 [0.22427845]
 [0.21585084]
 [0.21459031]
 [0.20622362]
 [0.2038486 ]
 [0.19209884]
 [0.18968585]
 [0.18793629]
 [0.17670989]
 [0.17364481]
 [0.16865554]
 [0.16362351]
 [0.16095082]
 [0.15771198]
 [0.15658213]
 [0.15229222]
 [0.15044613]
 [0.14846197]
 [0.14625879]
 [0.1442948 ]
 [0.14320725]
 [0.14224292]
 [0.14081049]
 [0.14075944]
 [0.13748232]
 [0.13584056]
 [0.13394736]
 [0.13376753]
 [0.13352795]
 [0.13231185]
 [0.1313091 ]
 [0.13077076]
 [0.1306067 ]
 [0.12500876]
 [0.12485375]
 [0.1238706 ]
 [0.12150306]
 [0.12107041]
 [0.11899471]
 [0.11894165]
 [0.11869835]
 [0.118099  ]
 [0.11708227]
 [0.11559407]
 [0.11332955]
 [0.11008213]
 [0.10908191]
 [0.10862021]
 [0.10836234]
 [0.10825495]
 [0.10811182]
 [0.10786147]
 [0.10752133]
 [0.10719242]
 [0.10647868]
 [0.10550317]
 [0.10525583]
 [0.10495735]
 [0.10470989]
 [0.10393839]
 [0.10

[[0.68791443]
 [0.6859605 ]
 [0.5084461 ]
 [0.39972103]
 [0.36325166]
 [0.35128215]
 [0.32267526]
 [0.31251693]
 [0.27344275]
 [0.27144283]
 [0.26872703]
 [0.23725548]
 [0.23027943]
 [0.22680694]
 [0.21871856]
 [0.20682986]
 [0.20331867]
 [0.19545393]
 [0.1892624 ]
 [0.18795861]
 [0.18389404]
 [0.18380778]
 [0.18153287]
 [0.17427853]
 [0.17238587]
 [0.17083113]
 [0.16164929]
 [0.15934502]
 [0.15810932]
 [0.157093  ]
 [0.15699561]
 [0.1563536 ]
 [0.15135375]
 [0.14714019]
 [0.14660506]
 [0.14174119]
 [0.1416311 ]
 [0.14040406]
 [0.13918109]
 [0.13897273]
 [0.13873468]
 [0.138665  ]
 [0.13757947]
 [0.13395149]
 [0.13305764]
 [0.1325158 ]
 [0.13141206]
 [0.1312888 ]
 [0.13046522]
 [0.12991533]
 [0.12450562]
 [0.12412143]
 [0.12391492]
 [0.12279841]
 [0.12196219]
 [0.12074451]
 [0.12021814]
 [0.11986953]
 [0.11918941]
 [0.11873142]
 [0.11867727]
 [0.11866627]
 [0.1174624 ]
 [0.11658513]
 [0.11648049]
 [0.11281833]
 [0.11265441]
 [0.11200947]
 [0.11147216]
 [0.11090562]
 [0.10923305]
 [0.10

[[0.6587918 ]
 [0.6583894 ]
 [0.3729666 ]
 [0.3061861 ]
 [0.29436716]
 [0.27384627]
 [0.2400607 ]
 [0.23320283]
 [0.2223842 ]
 [0.21896018]
 [0.21374534]
 [0.21019286]
 [0.19831385]
 [0.19338521]
 [0.1872707 ]
 [0.18597138]
 [0.17926675]
 [0.17921081]
 [0.17865908]
 [0.17469572]
 [0.17431758]
 [0.16501942]
 [0.16465583]
 [0.16333637]
 [0.16253485]
 [0.16237853]
 [0.16045196]
 [0.15529816]
 [0.15325588]
 [0.15030722]
 [0.1478432 ]
 [0.14519973]
 [0.14345337]
 [0.14195623]
 [0.14186378]
 [0.13983414]
 [0.13948153]
 [0.13904221]
 [0.13854028]
 [0.13551274]
 [0.13210374]
 [0.13023613]
 [0.13017668]
 [0.1281372 ]
 [0.12759991]
 [0.12714382]
 [0.12407716]
 [0.12310816]
 [0.11699098]
 [0.11627804]
 [0.1160613 ]
 [0.11557856]
 [0.11306357]
 [0.11305867]
 [0.11219919]
 [0.11143309]
 [0.11019699]
 [0.11013024]
 [0.10997236]
 [0.1091463 ]
 [0.10886361]
 [0.1064207 ]
 [0.10613662]
 [0.10481746]
 [0.1032286 ]
 [0.10315   ]
 [0.10261891]
 [0.10232511]
 [0.10187625]
 [0.10133246]
 [0.10122956]
 [0.10

[[0.69502056]
 [0.66727835]
 [0.39793125]
 [0.37305793]
 [0.32004425]
 [0.31623986]
 [0.2711864 ]
 [0.26166123]
 [0.25671473]
 [0.25639427]
 [0.23959725]
 [0.2279166 ]
 [0.22440812]
 [0.21843642]
 [0.20661412]
 [0.202401  ]
 [0.20200889]
 [0.19894764]
 [0.18324004]
 [0.17725186]
 [0.17393665]
 [0.17024152]
 [0.16555427]
 [0.15980366]
 [0.15878007]
 [0.15864876]
 [0.1572145 ]
 [0.15615092]
 [0.15533458]
 [0.15417905]
 [0.1509037 ]
 [0.14999814]
 [0.14863506]
 [0.14855844]
 [0.14759657]
 [0.14715505]
 [0.145995  ]
 [0.1447869 ]
 [0.14473523]
 [0.14433447]
 [0.14431903]
 [0.14277166]
 [0.14247009]
 [0.13603865]
 [0.13571136]
 [0.13503617]
 [0.13328856]
 [0.13091236]
 [0.130604  ]
 [0.1300012 ]
 [0.126731  ]
 [0.12585334]
 [0.12413294]
 [0.12310146]
 [0.12278221]
 [0.12241986]
 [0.12217106]
 [0.12127427]
 [0.12119399]
 [0.12052808]
 [0.11944003]
 [0.11912439]
 [0.11848718]
 [0.11552796]
 [0.11319375]
 [0.11303795]
 [0.11205591]
 [0.11012887]
 [0.10961395]
 [0.10911988]
 [0.10870703]
 [0.10

[[0.68198013]
 [0.65862864]
 [0.3480764 ]
 [0.3435596 ]
 [0.28713483]
 [0.28447083]
 [0.2829862 ]
 [0.2828777 ]
 [0.26736718]
 [0.2638718 ]
 [0.2239094 ]
 [0.21762419]
 [0.212207  ]
 [0.20769387]
 [0.20628476]
 [0.19471014]
 [0.1929162 ]
 [0.1910007 ]
 [0.18699215]
 [0.1804559 ]
 [0.17936628]
 [0.17429617]
 [0.16623679]
 [0.1656804 ]
 [0.1644289 ]
 [0.16298378]
 [0.1612522 ]
 [0.15998657]
 [0.15680438]
 [0.15594049]
 [0.15579206]
 [0.15521088]
 [0.15309261]
 [0.14936274]
 [0.14919394]
 [0.14735095]
 [0.14703505]
 [0.14606145]
 [0.14299513]
 [0.14012037]
 [0.1373606 ]
 [0.13672177]
 [0.13410951]
 [0.13331208]
 [0.1332171 ]
 [0.13187008]
 [0.13043459]
 [0.13039611]
 [0.12912937]
 [0.12563416]
 [0.12491252]
 [0.12404601]
 [0.12235545]
 [0.12174606]
 [0.12077238]
 [0.12045957]
 [0.11785156]
 [0.11532204]
 [0.11432917]
 [0.11278698]
 [0.11270529]
 [0.11223419]
 [0.11196098]
 [0.11094987]
 [0.11076555]
 [0.11034742]
 [0.11010365]
 [0.10782915]
 [0.10633296]
 [0.10618737]
 [0.10580503]
 [0.10

[[0.6897206 ]
 [0.6669781 ]
 [0.34270644]
 [0.3143566 ]
 [0.30296835]
 [0.28560528]
 [0.2732795 ]
 [0.27235007]
 [0.26290315]
 [0.22907397]
 [0.21517505]
 [0.20902163]
 [0.20603551]
 [0.19399932]
 [0.19149567]
 [0.18794018]
 [0.18564685]
 [0.1850053 ]
 [0.168728  ]
 [0.16577855]
 [0.16438258]
 [0.16349791]
 [0.16298252]
 [0.16112994]
 [0.1598281 ]
 [0.1561174 ]
 [0.15541358]
 [0.15501682]
 [0.15418749]
 [0.15182988]
 [0.1504093 ]
 [0.14783913]
 [0.14374836]
 [0.14253294]
 [0.14226294]
 [0.14108312]
 [0.14012879]
 [0.13962716]
 [0.13898627]
 [0.1331332 ]
 [0.13284965]
 [0.1307498 ]
 [0.12702501]
 [0.12483299]
 [0.12448861]
 [0.12407383]
 [0.12312068]
 [0.12302598]
 [0.12183417]
 [0.12146078]
 [0.12090275]
 [0.11832019]
 [0.11757857]
 [0.11724823]
 [0.11462744]
 [0.11341527]
 [0.11273541]
 [0.11255129]
 [0.11142059]
 [0.11104642]
 [0.11091499]
 [0.11057801]
 [0.10958245]
 [0.10958218]
 [0.10902417]
 [0.10795197]
 [0.10347441]
 [0.10301976]
 [0.10142796]
 [0.10015629]]
[[0.6805182 ]
 [0.6

[[0.7116443 ]
 [0.67200524]
 [0.3557214 ]
 [0.33579993]
 [0.3041786 ]
 [0.30160168]
 [0.29263756]
 [0.27919197]
 [0.26573962]
 [0.23315601]
 [0.22232892]
 [0.20781556]
 [0.20462435]
 [0.19737004]
 [0.1953133 ]
 [0.19122268]
 [0.1787243 ]
 [0.17811684]
 [0.17590243]
 [0.16853173]
 [0.16823196]
 [0.16712743]
 [0.16647412]
 [0.16392075]
 [0.16282576]
 [0.1623185 ]
 [0.16149783]
 [0.15440099]
 [0.14680727]
 [0.14464329]
 [0.14382118]
 [0.14329863]
 [0.14326629]
 [0.14320357]
 [0.14288583]
 [0.14217062]
 [0.14163548]
 [0.14135966]
 [0.13776478]
 [0.13733329]
 [0.13707933]
 [0.13609284]
 [0.13556981]
 [0.1338101 ]
 [0.13295268]
 [0.13269857]
 [0.13258082]
 [0.13005722]
 [0.12968849]
 [0.12859693]
 [0.12788235]
 [0.12607245]
 [0.1259246 ]
 [0.1250511 ]
 [0.12404659]
 [0.1236666 ]
 [0.12095346]
 [0.12067687]
 [0.11903435]
 [0.11894158]
 [0.11663415]
 [0.11575754]
 [0.11412044]
 [0.11358271]
 [0.113395  ]
 [0.11296228]
 [0.11211618]
 [0.11178563]
 [0.11177888]
 [0.11164238]
 [0.11020821]
 [0.11

[[0.6942102 ]
 [0.661567  ]
 [0.35692766]
 [0.31099632]
 [0.304587  ]
 [0.28787565]
 [0.278231  ]
 [0.25993767]
 [0.25054678]
 [0.23057091]
 [0.21756963]
 [0.20828214]
 [0.20692381]
 [0.20023474]
 [0.19272415]
 [0.17499575]
 [0.17310135]
 [0.17304437]
 [0.16978928]
 [0.16762811]
 [0.16476506]
 [0.16469939]
 [0.16463096]
 [0.1640265 ]
 [0.16266164]
 [0.1585845 ]
 [0.15402597]
 [0.15166605]
 [0.15069416]
 [0.14977445]
 [0.14949897]
 [0.1459147 ]
 [0.1440805 ]
 [0.14392665]
 [0.14172281]
 [0.1400713 ]
 [0.13890916]
 [0.13782637]
 [0.13697873]
 [0.13547648]
 [0.1338958 ]
 [0.13043582]
 [0.12933473]
 [0.12775894]
 [0.12747243]
 [0.1262724 ]
 [0.12526685]
 [0.12409846]
 [0.12343212]
 [0.12205682]
 [0.12104224]
 [0.11997135]
 [0.11955999]
 [0.11907104]
 [0.11565775]
 [0.11525121]
 [0.11509679]
 [0.11194914]
 [0.11038098]
 [0.11001003]
 [0.10945047]
 [0.10771008]
 [0.10566026]
 [0.10426401]
 [0.10390853]
 [0.1027716 ]
 [0.102575  ]
 [0.10192535]
 [0.10146131]
 [0.10105199]]
[[0.68599737]
 [0.6

[[0.68672675]
 [0.67328656]
 [0.33099252]
 [0.3244493 ]
 [0.3012829 ]
 [0.2819319 ]
 [0.25616857]
 [0.2317036 ]
 [0.2267691 ]
 [0.2128743 ]
 [0.21188809]
 [0.21181116]
 [0.21137346]
 [0.20752831]
 [0.20592827]
 [0.20271704]
 [0.19799061]
 [0.1972884 ]
 [0.19552411]
 [0.19120458]
 [0.18466832]
 [0.17274424]
 [0.16298807]
 [0.16220632]
 [0.15984435]
 [0.15646277]
 [0.15601917]
 [0.15595311]
 [0.15573806]
 [0.154762  ]
 [0.14756347]
 [0.14534003]
 [0.14475901]
 [0.14474197]
 [0.1415801 ]
 [0.13955471]
 [0.13707171]
 [0.1355297 ]
 [0.13541007]
 [0.13524996]
 [0.13443972]
 [0.13141815]
 [0.12786767]
 [0.12769902]
 [0.12412083]
 [0.12368416]
 [0.12366272]
 [0.12225974]
 [0.12225849]
 [0.12218027]
 [0.12086301]
 [0.12065597]
 [0.11955058]
 [0.11946921]
 [0.11729544]
 [0.11677966]
 [0.11664972]
 [0.11605169]
 [0.11466338]
 [0.1145753 ]
 [0.11399119]
 [0.11323734]
 [0.11295389]
 [0.11054406]
 [0.10973384]
 [0.10956986]
 [0.10917304]
 [0.10882133]
 [0.10876803]
 [0.10465138]
 [0.10432965]
 [0.10

[[0.6770948 ]
 [0.66607547]
 [0.35778278]
 [0.33925733]
 [0.31537178]
 [0.30537558]
 [0.29039305]
 [0.2737512 ]
 [0.24190725]
 [0.21982177]
 [0.21053523]
 [0.20369284]
 [0.2021649 ]
 [0.1957607 ]
 [0.19074172]
 [0.18980063]
 [0.18727666]
 [0.1854559 ]
 [0.177905  ]
 [0.17069215]
 [0.16614972]
 [0.16437262]
 [0.16401285]
 [0.15955426]
 [0.15547813]
 [0.15448302]
 [0.15145409]
 [0.14821902]
 [0.14633922]
 [0.14572215]
 [0.1455165 ]
 [0.1449554 ]
 [0.14250931]
 [0.14167419]
 [0.13864799]
 [0.13762769]
 [0.13734303]
 [0.13723819]
 [0.1339664 ]
 [0.13385303]
 [0.13164301]
 [0.12853977]
 [0.12519555]
 [0.12417845]
 [0.12413273]
 [0.12373757]
 [0.12295218]
 [0.12262835]
 [0.12080831]
 [0.12024941]
 [0.11944733]
 [0.1194104 ]
 [0.11868365]
 [0.11735404]
 [0.11707862]
 [0.11665076]
 [0.1146713 ]
 [0.11364324]
 [0.11122173]
 [0.11029191]
 [0.10927945]
 [0.10894524]
 [0.10860891]
 [0.10848954]
 [0.10827202]
 [0.10804336]
 [0.10789882]
 [0.10684837]
 [0.10568502]
 [0.10464036]
 [0.10413118]
 [0.10

[[0.6672255 ]
 [0.66115105]
 [0.3221561 ]
 [0.297263  ]
 [0.27282742]
 [0.26955834]
 [0.24941051]
 [0.23396277]
 [0.23244332]
 [0.22438706]
 [0.2098789 ]
 [0.20702279]
 [0.2063249 ]
 [0.20065026]
 [0.19926654]
 [0.19719149]
 [0.19648622]
 [0.1853054 ]
 [0.18289848]
 [0.17763445]
 [0.1776052 ]
 [0.17449155]
 [0.17334679]
 [0.17318757]
 [0.16017802]
 [0.15635891]
 [0.1553135 ]
 [0.1522726 ]
 [0.15213688]
 [0.14894074]
 [0.14886275]
 [0.14837916]
 [0.14558424]
 [0.14195427]
 [0.14184526]
 [0.14130649]
 [0.14020969]
 [0.13956095]
 [0.13917504]
 [0.1326179 ]
 [0.13108253]
 [0.12745859]
 [0.12608565]
 [0.12608337]
 [0.12416017]
 [0.12394416]
 [0.1220571 ]
 [0.12136693]
 [0.11992684]
 [0.11888603]
 [0.11708515]
 [0.11658739]
 [0.11651929]
 [0.11467936]
 [0.11466747]
 [0.11303666]
 [0.11210918]
 [0.11159182]
 [0.1112927 ]
 [0.11112903]
 [0.10965969]
 [0.10925761]
 [0.10856769]
 [0.10741084]
 [0.10734268]
 [0.10670873]
 [0.10664945]
 [0.10570472]
 [0.10507572]
 [0.10498328]
 [0.10459616]
 [0.10

[[0.7064422 ]
 [0.6677406 ]
 [0.32025206]
 [0.31970727]
 [0.31749701]
 [0.27712673]
 [0.2595717 ]
 [0.25657368]
 [0.22743547]
 [0.21443786]
 [0.21087925]
 [0.20383453]
 [0.19356874]
 [0.1868128 ]
 [0.18654919]
 [0.17904343]
 [0.17604235]
 [0.1734729 ]
 [0.17214616]
 [0.16798954]
 [0.16761473]
 [0.16434327]
 [0.15491498]
 [0.15069465]
 [0.14952691]
 [0.1460802 ]
 [0.14592068]
 [0.14404555]
 [0.1428956 ]
 [0.14245616]
 [0.13590115]
 [0.13354082]
 [0.13298619]
 [0.13234603]
 [0.13068159]
 [0.12934096]
 [0.12815706]
 [0.12679698]
 [0.12607916]
 [0.12429541]
 [0.1233924 ]
 [0.12278184]
 [0.1215784 ]
 [0.12110199]
 [0.11930639]
 [0.1157808 ]
 [0.11529731]
 [0.11400936]
 [0.11396797]
 [0.11321259]
 [0.1130982 ]
 [0.11202036]
 [0.11148043]
 [0.11113949]
 [0.11005472]
 [0.10861646]
 [0.10807088]
 [0.10682284]
 [0.10573009]
 [0.10466927]
 [0.10387716]
 [0.10327449]
 [0.10258552]
 [0.10196582]
 [0.10089638]
 [0.10072862]
 [0.1006525 ]]
[[0.6913483 ]
 [0.6585921 ]
 [0.29823416]
 [0.2896183 ]
 [0.2

[[0.68045574]
 [0.6561476 ]
 [0.2751003 ]
 [0.27412003]
 [0.2639532 ]
 [0.2580517 ]
 [0.25741607]
 [0.24951148]
 [0.24847254]
 [0.24160737]
 [0.22470067]
 [0.216547  ]
 [0.18855645]
 [0.1828078 ]
 [0.1816405 ]
 [0.1757342 ]
 [0.17504263]
 [0.17434333]
 [0.1684042 ]
 [0.16825607]
 [0.16819482]
 [0.15775606]
 [0.15642214]
 [0.15615524]
 [0.1496195 ]
 [0.1481799 ]
 [0.14528213]
 [0.14387439]
 [0.14121251]
 [0.14109178]
 [0.14034867]
 [0.1389627 ]
 [0.1380233 ]
 [0.1369967 ]
 [0.13612412]
 [0.13587078]
 [0.13529313]
 [0.13500296]
 [0.13048851]
 [0.12984428]
 [0.12781605]
 [0.12672569]
 [0.12667745]
 [0.12619756]
 [0.12501231]
 [0.12314209]
 [0.12303911]
 [0.12132769]
 [0.11907389]
 [0.11828717]
 [0.11738894]
 [0.11659683]
 [0.1146809 ]
 [0.11289413]
 [0.1126514 ]
 [0.11083372]
 [0.11003572]
 [0.10969713]
 [0.10964539]
 [0.1095585 ]
 [0.10953739]
 [0.10847836]
 [0.10745599]
 [0.10708922]
 [0.10508868]
 [0.1037489 ]
 [0.1035846 ]
 [0.10351781]
 [0.10267064]
 [0.10205939]
 [0.10096843]]
[[0.7

[[0.71953404]
 [0.66798294]
 [0.33734298]
 [0.3134457 ]
 [0.3109654 ]
 [0.2682604 ]
 [0.2588812 ]
 [0.24544497]
 [0.23348042]
 [0.23269497]
 [0.21974479]
 [0.2074459 ]
 [0.1979145 ]
 [0.19763954]
 [0.19284593]
 [0.19216347]
 [0.18629855]
 [0.17326924]
 [0.16989408]
 [0.16570172]
 [0.1631059 ]
 [0.16287327]
 [0.16238225]
 [0.158691  ]
 [0.15288162]
 [0.15272182]
 [0.15244778]
 [0.14733115]
 [0.14675723]
 [0.14525156]
 [0.14480817]
 [0.14283088]
 [0.14131415]
 [0.14079468]
 [0.13957678]
 [0.13824332]
 [0.13772896]
 [0.1374579 ]
 [0.1373279 ]
 [0.13698103]
 [0.13697511]
 [0.13482174]
 [0.12968268]
 [0.1274402 ]
 [0.12743026]
 [0.1269788 ]
 [0.12584376]
 [0.12566808]
 [0.12507913]
 [0.12234212]
 [0.12199295]
 [0.1211863 ]
 [0.120757  ]
 [0.12001021]
 [0.11881991]
 [0.11641294]
 [0.11546937]
 [0.11133199]
 [0.11075322]
 [0.10939115]
 [0.10906015]
 [0.10798019]
 [0.10793439]
 [0.10749714]
 [0.10742527]
 [0.10579856]
 [0.10545804]
 [0.1053043 ]
 [0.10504668]
 [0.10418293]
 [0.10309204]
 [0.10

[[0.6956196 ]
 [0.6569498 ]
 [0.31803918]
 [0.30717322]
 [0.3014054 ]
 [0.27043092]
 [0.2671885 ]
 [0.25447294]
 [0.24939476]
 [0.23478025]
 [0.23210575]
 [0.21238062]
 [0.20755985]
 [0.19890021]
 [0.19586511]
 [0.1941499 ]
 [0.1929006 ]
 [0.18692297]
 [0.18415469]
 [0.18242134]
 [0.1821238 ]
 [0.16834803]
 [0.15952834]
 [0.15929526]
 [0.15687017]
 [0.15390185]
 [0.15287994]
 [0.1503451 ]
 [0.1493559 ]
 [0.1487771 ]
 [0.14870326]
 [0.14765647]
 [0.14612286]
 [0.14507851]
 [0.14400084]
 [0.14307314]
 [0.14277977]
 [0.1421378 ]
 [0.14104827]
 [0.14049616]
 [0.13931094]
 [0.13813367]
 [0.13753985]
 [0.1357293 ]
 [0.1331292 ]
 [0.13264854]
 [0.13166276]
 [0.12965125]
 [0.1267023 ]
 [0.12603608]
 [0.12275415]
 [0.12256902]
 [0.12225465]
 [0.12174943]
 [0.12120691]
 [0.11870747]
 [0.11869407]
 [0.11813797]
 [0.11794196]
 [0.1173338 ]
 [0.11701079]
 [0.11494666]
 [0.11427333]
 [0.11084798]
 [0.10784225]
 [0.10709969]
 [0.1068344 ]
 [0.10659839]
 [0.10635997]
 [0.10628908]
 [0.10525719]
 [0.10

[[0.6894607 ]
 [0.6573382 ]
 [0.3344746 ]
 [0.31676322]
 [0.30985433]
 [0.27807108]
 [0.26828334]
 [0.26637554]
 [0.24204227]
 [0.20908251]
 [0.20118429]
 [0.19654155]
 [0.19458967]
 [0.1931409 ]
 [0.19288798]
 [0.19193582]
 [0.18818156]
 [0.18309173]
 [0.1784584 ]
 [0.1779055 ]
 [0.17374511]
 [0.16993292]
 [0.16953306]
 [0.16619423]
 [0.16460864]
 [0.16294526]
 [0.16117746]
 [0.16048269]
 [0.15581629]
 [0.1557976 ]
 [0.15292689]
 [0.1508431 ]
 [0.14949095]
 [0.14915793]
 [0.14841624]
 [0.14806724]
 [0.14400707]
 [0.14238848]
 [0.13988589]
 [0.13794224]
 [0.13636518]
 [0.13540936]
 [0.13486607]
 [0.13474014]
 [0.13437934]
 [0.13427784]
 [0.13363284]
 [0.13207053]
 [0.12923881]
 [0.12776388]
 [0.12773007]
 [0.12665568]
 [0.12539166]
 [0.12508477]
 [0.1249871 ]
 [0.12481388]
 [0.12289419]
 [0.1213469 ]
 [0.1209023 ]
 [0.11953387]
 [0.11907696]
 [0.11816107]
 [0.11545857]
 [0.11493277]
 [0.11482262]
 [0.11432955]
 [0.11348773]
 [0.11326161]
 [0.1130293 ]
 [0.11022916]
 [0.10823709]
 [0.10

[[0.6628539 ]
 [0.6583242 ]
 [0.30475047]
 [0.28379256]
 [0.27586672]
 [0.26982182]
 [0.26621222]
 [0.26544586]
 [0.2624816 ]
 [0.25149652]
 [0.2220942 ]
 [0.20930266]
 [0.20555115]
 [0.2018    ]
 [0.18953685]
 [0.18863732]
 [0.17837946]
 [0.17458345]
 [0.1626921 ]
 [0.16091721]
 [0.15995327]
 [0.15903327]
 [0.1529777 ]
 [0.15268973]
 [0.15211757]
 [0.1515609 ]
 [0.15087351]
 [0.14914651]
 [0.14748783]
 [0.14187427]
 [0.14073108]
 [0.14049146]
 [0.13964269]
 [0.13883254]
 [0.13807644]
 [0.13523075]
 [0.13481452]
 [0.13456868]
 [0.1339807 ]
 [0.1311995 ]
 [0.13096756]
 [0.13058896]
 [0.12984635]
 [0.12770553]
 [0.1275542 ]
 [0.12685147]
 [0.12610836]
 [0.12573983]
 [0.12383173]
 [0.12350553]
 [0.12295966]
 [0.12295247]
 [0.12276142]
 [0.12085719]
 [0.12034076]
 [0.11862994]
 [0.11755576]
 [0.11613979]
 [0.11563675]
 [0.11401117]
 [0.113108  ]
 [0.11205798]
 [0.11100777]
 [0.10983991]
 [0.10925931]
 [0.10889865]
 [0.1080986 ]
 [0.10718722]
 [0.10548493]
 [0.10451142]
 [0.10444331]
 [0.10

[[0.6621519 ]
 [0.6588522 ]
 [0.3233106 ]
 [0.32029307]
 [0.31036755]
 [0.277168  ]
 [0.26325065]
 [0.26081878]
 [0.24341182]
 [0.2418736 ]
 [0.19848414]
 [0.19614036]
 [0.1934008 ]
 [0.18846034]
 [0.18740879]
 [0.18551815]
 [0.18337488]
 [0.18110815]
 [0.17383131]
 [0.17329045]
 [0.16357428]
 [0.15955175]
 [0.15668799]
 [0.15551805]
 [0.15437049]
 [0.14767317]
 [0.1468797 ]
 [0.14616497]
 [0.1430073 ]
 [0.14086016]
 [0.14069624]
 [0.14015053]
 [0.13932022]
 [0.13909726]
 [0.138638  ]
 [0.13853051]
 [0.13769387]
 [0.13599429]
 [0.13412118]
 [0.13207725]
 [0.1292418 ]
 [0.12475602]
 [0.12458274]
 [0.12194775]
 [0.12111256]
 [0.11881918]
 [0.11868151]
 [0.11722588]
 [0.11595628]
 [0.11457157]
 [0.11363433]
 [0.11323238]
 [0.11267095]
 [0.11114796]
 [0.1106158 ]
 [0.11031961]
 [0.11009338]
 [0.10970265]
 [0.1094941 ]
 [0.10880917]
 [0.10765132]
 [0.10577732]
 [0.10357393]
 [0.10309052]
 [0.10229103]
 [0.10167693]
 [0.10130257]
 [0.10109213]
 [0.1004125 ]]
[[0.71258104]
 [0.650988  ]
 [0.3

[[0.66900325]
 [0.6573212 ]
 [0.35459048]
 [0.329408  ]
 [0.32228845]
 [0.26793775]
 [0.26726186]
 [0.24744157]
 [0.2414337 ]
 [0.22471884]
 [0.21318729]
 [0.21129861]
 [0.20894596]
 [0.20161112]
 [0.18633972]
 [0.1859246 ]
 [0.184814  ]
 [0.17255771]
 [0.17046365]
 [0.16865557]
 [0.16389291]
 [0.16215846]
 [0.15750042]
 [0.155861  ]
 [0.15580662]
 [0.15301168]
 [0.15285812]
 [0.14979026]
 [0.14846465]
 [0.14806046]
 [0.14763783]
 [0.1440638 ]
 [0.14298066]
 [0.14016971]
 [0.13834497]
 [0.13686927]
 [0.1362162 ]
 [0.13536592]
 [0.13510992]
 [0.13480277]
 [0.13325551]
 [0.13308434]
 [0.13089684]
 [0.12642218]
 [0.12598692]
 [0.12531114]
 [0.12483838]
 [0.12083888]
 [0.11842985]
 [0.11657552]
 [0.11578434]
 [0.11505263]
 [0.11379687]
 [0.11376235]
 [0.11256028]
 [0.11235191]
 [0.110903  ]
 [0.11046453]
 [0.1104252 ]
 [0.11019425]
 [0.10915264]
 [0.10877196]
 [0.10875294]
 [0.10818332]
 [0.10772502]
 [0.10764428]
 [0.10696635]
 [0.10610197]
 [0.10448445]
 [0.10331109]
 [0.10326176]
 [0.10

[[0.72419494]
 [0.697169  ]
 [0.47420165]
 [0.38797098]
 [0.33258572]
 [0.32182887]
 [0.29653737]
 [0.2958662 ]
 [0.29017743]
 [0.28088373]
 [0.2702809 ]
 [0.26820433]
 [0.24168026]
 [0.22120485]
 [0.21703236]
 [0.21669328]
 [0.21441421]
 [0.21220577]
 [0.21208212]
 [0.21091953]
 [0.20465977]
 [0.20304698]
 [0.1999926 ]
 [0.19981349]
 [0.19949158]
 [0.19863656]
 [0.1974482 ]
 [0.19232577]
 [0.19151735]
 [0.1855602 ]
 [0.17941226]
 [0.17907527]
 [0.1754577 ]
 [0.17478003]
 [0.17357539]
 [0.17135005]
 [0.16979028]
 [0.16832116]
 [0.16779321]
 [0.16715208]
 [0.16613074]
 [0.16350028]
 [0.16262013]
 [0.16180876]
 [0.15917748]
 [0.1583865 ]
 [0.1580511 ]
 [0.15624188]
 [0.15522671]
 [0.1549386 ]
 [0.15403865]
 [0.1518864 ]
 [0.1493529 ]
 [0.1491882 ]
 [0.14754763]
 [0.14652051]
 [0.14609402]
 [0.14588134]
 [0.14550203]
 [0.14380948]
 [0.14292182]
 [0.14242186]
 [0.14161421]
 [0.13977292]
 [0.13903953]
 [0.1378216 ]
 [0.13551147]
 [0.13457988]
 [0.1342045 ]
 [0.13403462]
 [0.13184151]
 [0.13

[[0.726737  ]
 [0.7076913 ]
 [0.44915074]
 [0.43291956]
 [0.32827196]
 [0.31040534]
 [0.281591  ]
 [0.2723104 ]
 [0.25434926]
 [0.24475498]
 [0.24438035]
 [0.24198966]
 [0.23335437]
 [0.22094691]
 [0.21332337]
 [0.2111677 ]
 [0.19517127]
 [0.19216153]
 [0.1876685 ]
 [0.18456444]
 [0.17847683]
 [0.17535836]
 [0.17190708]
 [0.16583899]
 [0.16561462]
 [0.16414177]
 [0.16225487]
 [0.15593387]
 [0.15422231]
 [0.15365419]
 [0.15354471]
 [0.15310408]
 [0.15295732]
 [0.15234427]
 [0.1508441 ]
 [0.15036352]
 [0.14976734]
 [0.14733353]
 [0.14678098]
 [0.14567967]
 [0.14553162]
 [0.14529468]
 [0.14442657]
 [0.14418063]
 [0.14303008]
 [0.1359864 ]
 [0.13454367]
 [0.13386093]
 [0.13216466]
 [0.13213179]
 [0.13097434]
 [0.12925617]
 [0.12903446]
 [0.12824652]
 [0.12792759]
 [0.12497119]
 [0.12188957]
 [0.12038539]
 [0.12016363]
 [0.12015729]
 [0.1177569 ]
 [0.11742514]
 [0.11687764]
 [0.11675303]
 [0.11545537]
 [0.11542463]
 [0.11528307]
 [0.11491674]
 [0.11455478]
 [0.11422332]
 [0.11400061]
 [0.11

[[0.7062465 ]
 [0.69984   ]
 [0.34638965]
 [0.3297018 ]
 [0.29236344]
 [0.2818038 ]
 [0.2568731 ]
 [0.24755871]
 [0.24737743]
 [0.24366285]
 [0.23045148]
 [0.22583582]
 [0.21895677]
 [0.21833277]
 [0.21069409]
 [0.20920238]
 [0.20748384]
 [0.2054356 ]
 [0.19473322]
 [0.19021189]
 [0.1866441 ]
 [0.18435436]
 [0.18328032]
 [0.18107398]
 [0.18006228]
 [0.17973252]
 [0.17955127]
 [0.17339465]
 [0.17327222]
 [0.17155084]
 [0.17093006]
 [0.17021103]
 [0.1696512 ]
 [0.16920719]
 [0.16847943]
 [0.16542968]
 [0.16398442]
 [0.16265942]
 [0.16152516]
 [0.15520464]
 [0.15505819]
 [0.15352896]
 [0.1521333 ]
 [0.15015161]
 [0.14589368]
 [0.14583014]
 [0.14427611]
 [0.14387646]
 [0.14374427]
 [0.14060809]
 [0.14011201]
 [0.13769975]
 [0.1369778 ]
 [0.13564761]
 [0.1355602 ]
 [0.1343558 ]
 [0.13255775]
 [0.13148314]
 [0.12937605]
 [0.12815847]
 [0.1274891 ]
 [0.12616678]
 [0.12492054]
 [0.12484337]
 [0.12463029]
 [0.12265857]
 [0.12241714]
 [0.12190588]
 [0.12182935]
 [0.12101839]
 [0.12063146]
 [0.12

[[0.73909473]
 [0.69635797]
 [0.33764225]
 [0.30042124]
 [0.29419592]
 [0.28868988]
 [0.27325267]
 [0.25116792]
 [0.23346272]
 [0.22428805]
 [0.22095892]
 [0.21429102]
 [0.19982809]
 [0.19883601]
 [0.1970441 ]
 [0.1955704 ]
 [0.19525559]
 [0.19377805]
 [0.18672952]
 [0.18232869]
 [0.17970896]
 [0.17863128]
 [0.17678139]
 [0.17663531]
 [0.17619687]
 [0.17564346]
 [0.17550951]
 [0.17420454]
 [0.17255452]
 [0.17227533]
 [0.17219763]
 [0.17100881]
 [0.16982307]
 [0.16710253]
 [0.16646418]
 [0.16477723]
 [0.16387175]
 [0.16102408]
 [0.16006994]
 [0.15725511]
 [0.15646467]
 [0.15363692]
 [0.14704743]
 [0.14570232]
 [0.14495802]
 [0.14285365]
 [0.13870195]
 [0.13645197]
 [0.13551879]
 [0.13542666]
 [0.1352786 ]
 [0.13313618]
 [0.13298418]
 [0.1323973 ]
 [0.13002625]
 [0.1299079 ]
 [0.12860379]
 [0.1285152 ]
 [0.1275708 ]
 [0.12687673]
 [0.12494674]
 [0.12432288]
 [0.12425285]
 [0.12316317]
 [0.12293463]
 [0.12274047]
 [0.12270933]
 [0.1219407 ]
 [0.12101328]
 [0.12067503]
 [0.120385  ]
 [0.12

[[0.7002608 ]
 [0.69154626]
 [0.3353577 ]
 [0.32613602]
 [0.24799144]
 [0.23603286]
 [0.23382066]
 [0.23281263]
 [0.21719435]
 [0.20691021]
 [0.2047618 ]
 [0.20433486]
 [0.20400053]
 [0.201069  ]
 [0.19849052]
 [0.19172354]
 [0.19083127]
 [0.18963802]
 [0.1895322 ]
 [0.18611732]
 [0.18529591]
 [0.18445183]
 [0.17445639]
 [0.17222865]
 [0.16980399]
 [0.16918667]
 [0.16917752]
 [0.16889364]
 [0.16503698]
 [0.16222553]
 [0.16176274]
 [0.16174014]
 [0.16030395]
 [0.16020548]
 [0.15999708]
 [0.1596326 ]
 [0.15638411]
 [0.15505058]
 [0.15169169]
 [0.15031306]
 [0.14800337]
 [0.14774536]
 [0.14738293]
 [0.1441757 ]
 [0.14158402]
 [0.13909575]
 [0.13830149]
 [0.13725258]
 [0.13255806]
 [0.12923664]
 [0.1290864 ]
 [0.12822741]
 [0.12811363]
 [0.12787509]
 [0.12650692]
 [0.12419576]
 [0.12244496]
 [0.12146641]
 [0.1212999 ]
 [0.12076622]
 [0.12047505]
 [0.11950645]
 [0.11910635]
 [0.11906352]
 [0.1186066 ]
 [0.11847337]
 [0.11826216]
 [0.11763346]
 [0.11633182]
 [0.11546299]
 [0.11416343]
 [0.11

[[0.7102538 ]
 [0.69641864]
 [0.30123815]
 [0.3003329 ]
 [0.26136968]
 [0.25388023]
 [0.24462953]
 [0.22975573]
 [0.22491597]
 [0.2162973 ]
 [0.21304336]
 [0.20875958]
 [0.19596525]
 [0.19446641]
 [0.19217962]
 [0.19155057]
 [0.19054656]
 [0.19040336]
 [0.19030757]
 [0.18615505]
 [0.18109739]
 [0.17884384]
 [0.17437425]
 [0.1696606 ]
 [0.16761668]
 [0.16679114]
 [0.16497888]
 [0.16353405]
 [0.16336402]
 [0.1630652 ]
 [0.16155773]
 [0.15986946]
 [0.15878004]
 [0.15808593]
 [0.15663376]
 [0.15414484]
 [0.14859688]
 [0.14758693]
 [0.14588484]
 [0.14163986]
 [0.14033507]
 [0.14010608]
 [0.13965748]
 [0.13879977]
 [0.13767661]
 [0.13611826]
 [0.13530499]
 [0.13421649]
 [0.13382076]
 [0.13041703]
 [0.1300221 ]
 [0.12923622]
 [0.12843215]
 [0.12783833]
 [0.12405387]
 [0.12231093]
 [0.12166622]
 [0.12148597]
 [0.11832071]
 [0.118077  ]
 [0.11805972]
 [0.11758798]
 [0.11706115]
 [0.11692782]
 [0.11644544]
 [0.1158477 ]
 [0.11556292]
 [0.11477491]
 [0.11460501]
 [0.11424483]
 [0.11214633]
 [0.11

[[0.72955436]
 [0.70756584]
 [0.3063897 ]
 [0.2740184 ]
 [0.26277506]
 [0.22761984]
 [0.22403167]
 [0.22126916]
 [0.21724747]
 [0.21668129]
 [0.21241246]
 [0.20890082]
 [0.2033122 ]
 [0.19978091]
 [0.1987495 ]
 [0.19227079]
 [0.18922633]
 [0.18706326]
 [0.18574545]
 [0.18185565]
 [0.18028969]
 [0.1750537 ]
 [0.17291057]
 [0.17263974]
 [0.16960837]
 [0.16910961]
 [0.16898628]
 [0.16605945]
 [0.16317804]
 [0.1628218 ]
 [0.16235195]
 [0.16161697]
 [0.15878277]
 [0.15594861]
 [0.15531273]
 [0.15496066]
 [0.15479776]
 [0.15359482]
 [0.15269387]
 [0.15081708]
 [0.14684881]
 [0.14435978]
 [0.14281784]
 [0.14055556]
 [0.13909025]
 [0.13737099]
 [0.13583204]
 [0.13567907]
 [0.13548587]
 [0.13197616]
 [0.12988152]
 [0.12957165]
 [0.12940472]
 [0.12781553]
 [0.12762156]
 [0.12747213]
 [0.12386158]
 [0.12190017]
 [0.12105212]
 [0.12100299]
 [0.12005502]
 [0.11773308]
 [0.11743949]
 [0.11716491]
 [0.1160773 ]
 [0.11538129]
 [0.11531642]
 [0.11480764]
 [0.11372184]
 [0.11141784]
 [0.11038627]
 [0.10

[[0.71955633]
 [0.6979233 ]
 [0.34254912]
 [0.3282702 ]
 [0.27112377]
 [0.26338243]
 [0.24782774]
 [0.21342422]
 [0.20350341]
 [0.19651641]
 [0.19514103]
 [0.18891768]
 [0.18121059]
 [0.17701767]
 [0.17507899]
 [0.17506574]
 [0.17377727]
 [0.17269535]
 [0.1718804 ]
 [0.17095703]
 [0.17078938]
 [0.17005633]
 [0.16971005]
 [0.16814779]
 [0.16620897]
 [0.166106  ]
 [0.16535857]
 [0.16174744]
 [0.16170004]
 [0.16169542]
 [0.16066515]
 [0.1599702 ]
 [0.15977068]
 [0.15933329]
 [0.15828277]
 [0.15767854]
 [0.15658133]
 [0.15275145]
 [0.15172465]
 [0.15124357]
 [0.14964944]
 [0.14960101]
 [0.14902242]
 [0.1478945 ]
 [0.14280428]
 [0.14078894]
 [0.13898647]
 [0.13733542]
 [0.13720702]
 [0.13700648]
 [0.13639644]
 [0.12993091]
 [0.1244144 ]
 [0.12379239]
 [0.11980865]
 [0.11956154]
 [0.11897039]
 [0.11872625]
 [0.1182054 ]
 [0.1162708 ]
 [0.11543418]
 [0.11393221]
 [0.11371408]
 [0.11366788]
 [0.10974576]
 [0.10846   ]
 [0.10833742]
 [0.10826015]
 [0.1080716 ]
 [0.10769127]
 [0.10713875]
 [0.10

[[0.71153647]
 [0.7035996 ]
 [0.40768254]
 [0.3458066 ]
 [0.24047743]
 [0.23081443]
 [0.22609013]
 [0.21424025]
 [0.21065003]
 [0.21022803]
 [0.20695837]
 [0.2018667 ]
 [0.19525808]
 [0.19081998]
 [0.18449634]
 [0.18425214]
 [0.18074581]
 [0.17543057]
 [0.17333162]
 [0.17197739]
 [0.16707498]
 [0.16557036]
 [0.16270176]
 [0.16263202]
 [0.16141066]
 [0.15965934]
 [0.1590007 ]
 [0.15502115]
 [0.15377627]
 [0.15271424]
 [0.15218072]
 [0.1509213 ]
 [0.14859922]
 [0.1481679 ]
 [0.14806479]
 [0.14693175]
 [0.14675565]
 [0.14644097]
 [0.14639981]
 [0.14605328]
 [0.14406587]
 [0.14291723]
 [0.1417917 ]
 [0.14098695]
 [0.14038049]
 [0.1403017 ]
 [0.1402349 ]
 [0.13977307]
 [0.13713846]
 [0.13461728]
 [0.13339353]
 [0.13219298]
 [0.13199039]
 [0.12944897]
 [0.12881279]
 [0.12538163]
 [0.12343449]
 [0.12324499]
 [0.1220696 ]
 [0.1217822 ]
 [0.12148398]
 [0.11768717]
 [0.11587486]
 [0.11582979]
 [0.1156541 ]
 [0.11480901]
 [0.11228326]
 [0.11160751]
 [0.1112005 ]
 [0.11107073]
 [0.11104973]
 [0.11

[[0.7080625 ]
 [0.7008879 ]
 [0.40633896]
 [0.35584158]
 [0.3094334 ]
 [0.27984154]
 [0.2698998 ]
 [0.24848261]
 [0.23061866]
 [0.22373396]
 [0.21832213]
 [0.2066788 ]
 [0.20658807]
 [0.19723767]
 [0.19300283]
 [0.1919419 ]
 [0.19176571]
 [0.1913215 ]
 [0.18290333]
 [0.16651918]
 [0.16527878]
 [0.16290049]
 [0.16205108]
 [0.16025563]
 [0.159068  ]
 [0.15761554]
 [0.15706566]
 [0.1551608 ]
 [0.15442003]
 [0.15436636]
 [0.1503801 ]
 [0.14766237]
 [0.14695475]
 [0.14540985]
 [0.14304428]
 [0.13898432]
 [0.13562654]
 [0.1354033 ]
 [0.13515955]
 [0.13478537]
 [0.13326788]
 [0.13104573]
 [0.13053703]
 [0.13048857]
 [0.12920763]
 [0.12824398]
 [0.12810706]
 [0.12793747]
 [0.12787417]
 [0.12660159]
 [0.12622459]
 [0.12621592]
 [0.12611133]
 [0.12597392]
 [0.12507114]
 [0.12442612]
 [0.12132496]
 [0.12032157]
 [0.12016518]
 [0.1195857 ]
 [0.11593524]
 [0.11543065]
 [0.11359762]
 [0.11281294]
 [0.11252711]
 [0.11199964]
 [0.11194284]
 [0.11170516]
 [0.11016788]
 [0.10913634]
 [0.10837632]
 [0.10

[[0.73703915]
 [0.70060974]
 [0.3742621 ]
 [0.2945143 ]
 [0.26109853]
 [0.25826213]
 [0.23576888]
 [0.22267556]
 [0.21819879]
 [0.21802568]
 [0.21420503]
 [0.20109749]
 [0.1941088 ]
 [0.18862826]
 [0.18398416]
 [0.18155807]
 [0.18080267]
 [0.17807913]
 [0.17711334]
 [0.17651771]
 [0.17499906]
 [0.1748078 ]
 [0.17120324]
 [0.16965736]
 [0.16902879]
 [0.16074105]
 [0.16071016]
 [0.15951295]
 [0.1586658 ]
 [0.15658921]
 [0.15426601]
 [0.15254164]
 [0.1520059 ]
 [0.15115547]
 [0.15038314]
 [0.14970249]
 [0.14906722]
 [0.14816976]
 [0.14768384]
 [0.14717619]
 [0.14413792]
 [0.14322317]
 [0.1417579 ]
 [0.1409658 ]
 [0.13769054]
 [0.13738123]
 [0.1367705 ]
 [0.13674282]
 [0.1361719 ]
 [0.13574874]
 [0.13035785]
 [0.12453119]
 [0.12299566]
 [0.12085526]
 [0.11945655]
 [0.11908738]
 [0.11789526]
 [0.11771571]
 [0.11699958]
 [0.11624826]
 [0.11551775]
 [0.11474821]
 [0.11446626]
 [0.1141642 ]
 [0.11335372]
 [0.11185472]
 [0.11015272]
 [0.10970368]
 [0.10958949]
 [0.10939371]
 [0.10920598]
 [0.10

[[0.73139495]
 [0.7051266 ]
 [0.31242332]
 [0.26126987]
 [0.2518952 ]
 [0.24120608]
 [0.23092616]
 [0.23047014]
 [0.22462322]
 [0.2209866 ]
 [0.21069868]
 [0.20626628]
 [0.2005313 ]
 [0.1950372 ]
 [0.19140323]
 [0.18958469]
 [0.188099  ]
 [0.18800773]
 [0.18551515]
 [0.18524368]
 [0.1825716 ]
 [0.17415844]
 [0.17409521]
 [0.17272457]
 [0.17235397]
 [0.17171942]
 [0.16964474]
 [0.16935854]
 [0.16619681]
 [0.16603528]
 [0.1646942 ]
 [0.16448537]
 [0.16129781]
 [0.15892224]
 [0.15852042]
 [0.15735051]
 [0.15453495]
 [0.15293016]
 [0.15101166]
 [0.14839858]
 [0.14799128]
 [0.14591272]
 [0.1404637 ]
 [0.1375845 ]
 [0.13704   ]
 [0.1357218 ]
 [0.13411821]
 [0.13403386]
 [0.13301262]
 [0.12989463]
 [0.12895945]
 [0.12815219]
 [0.12792668]
 [0.1278405 ]
 [0.12782781]
 [0.12723602]
 [0.12548815]
 [0.12423158]
 [0.12336636]
 [0.12167587]
 [0.1210543 ]
 [0.11851694]
 [0.11761647]
 [0.11681452]
 [0.11657909]
 [0.11645512]
 [0.11546376]
 [0.11488679]
 [0.11325572]
 [0.11303572]
 [0.11301108]
 [0.11

[[0.73080283]
 [0.69862866]
 [0.3677461 ]
 [0.30631435]
 [0.27913523]
 [0.25971377]
 [0.21945673]
 [0.21483192]
 [0.21275143]
 [0.21149713]
 [0.2049647 ]
 [0.20035155]
 [0.18791915]
 [0.18133263]
 [0.17799002]
 [0.17629589]
 [0.17623997]
 [0.17350039]
 [0.17129865]
 [0.16694644]
 [0.16518104]
 [0.16239963]
 [0.15904558]
 [0.15693651]
 [0.15577741]
 [0.15449639]
 [0.15417284]
 [0.1540179 ]
 [0.15307692]
 [0.15216519]
 [0.1488486 ]
 [0.14870782]
 [0.14854719]
 [0.1480271 ]
 [0.14795648]
 [0.14446488]
 [0.14415433]
 [0.14299443]
 [0.14179213]
 [0.14005241]
 [0.14000846]
 [0.13724752]
 [0.13615444]
 [0.1360259 ]
 [0.13494231]
 [0.1345836 ]
 [0.13324228]
 [0.13117391]
 [0.13020912]
 [0.1281445 ]
 [0.12547757]
 [0.12497408]
 [0.12490001]
 [0.12045293]
 [0.11881177]
 [0.11801197]
 [0.11790781]
 [0.11741292]
 [0.11680926]
 [0.11559266]
 [0.11465072]
 [0.11449097]
 [0.11426821]
 [0.11278052]
 [0.11245791]
 [0.11165008]
 [0.11159307]
 [0.11097809]
 [0.10991073]
 [0.10957599]
 [0.10890594]
 [0.10

[[0.74420875]
 [0.7054909 ]
 [0.2923648 ]
 [0.28334877]
 [0.23907636]
 [0.23213503]
 [0.22374082]
 [0.21213506]
 [0.20858432]
 [0.20680952]
 [0.19900079]
 [0.19643034]
 [0.19221699]
 [0.19093464]
 [0.18730772]
 [0.18689209]
 [0.1844785 ]
 [0.18397783]
 [0.18289705]
 [0.18289366]
 [0.18222678]
 [0.1755416 ]
 [0.16968901]
 [0.16709273]
 [0.16366716]
 [0.16209736]
 [0.16194019]
 [0.16130996]
 [0.16043113]
 [0.15938884]
 [0.15932344]
 [0.15886466]
 [0.1579547 ]
 [0.15481186]
 [0.15467937]
 [0.15081474]
 [0.15036798]
 [0.14926915]
 [0.14857142]
 [0.1466579 ]
 [0.14575979]
 [0.14210601]
 [0.14192739]
 [0.14153679]
 [0.14032295]
 [0.13637316]
 [0.13543734]
 [0.1343784 ]
 [0.13364229]
 [0.13214727]
 [0.12991802]
 [0.1292553 ]
 [0.12781206]
 [0.12736806]
 [0.12714873]
 [0.12700778]
 [0.12405241]
 [0.12294817]
 [0.12215023]
 [0.12164409]
 [0.12135011]
 [0.12115219]
 [0.11828754]
 [0.11762942]
 [0.1168767 ]
 [0.11594371]
 [0.11547573]
 [0.11541981]
 [0.11448531]
 [0.11436728]
 [0.11391158]
 [0.11

[[0.7423279 ]
 [0.7026507 ]
 [0.31014043]
 [0.30909684]
 [0.2721177 ]
 [0.26972476]
 [0.2512802 ]
 [0.23342523]
 [0.23193564]
 [0.21394171]
 [0.20992605]
 [0.20549233]
 [0.20402479]
 [0.19972467]
 [0.19691716]
 [0.1892397 ]
 [0.1886265 ]
 [0.18399249]
 [0.18046674]
 [0.17942038]
 [0.1776737 ]
 [0.17436305]
 [0.1706568 ]
 [0.16976301]
 [0.16776818]
 [0.16741285]
 [0.16583334]
 [0.16529472]
 [0.16464758]
 [0.16352776]
 [0.15912455]
 [0.15817967]
 [0.15704474]
 [0.15667793]
 [0.15645187]
 [0.15604089]
 [0.15382777]
 [0.15329401]
 [0.15173492]
 [0.14754552]
 [0.14687935]
 [0.14345753]
 [0.14332849]
 [0.142606  ]
 [0.14241804]
 [0.1408352 ]
 [0.13697271]
 [0.13646658]
 [0.13365641]
 [0.1334432 ]
 [0.13172981]
 [0.13157697]
 [0.13107277]
 [0.13071807]
 [0.12877819]
 [0.12860724]
 [0.12841044]
 [0.12269316]
 [0.12257085]
 [0.11909707]
 [0.1189519 ]
 [0.11828351]
 [0.11793042]
 [0.117183  ]
 [0.11698123]
 [0.1167815 ]
 [0.11659804]
 [0.11609076]
 [0.11570001]
 [0.11458059]
 [0.11384381]
 [0.11

[[0.70924526]
 [0.7023027 ]
 [0.26855037]
 [0.25733456]
 [0.239015  ]
 [0.23296538]
 [0.2319194 ]
 [0.2143492 ]
 [0.21078706]
 [0.21008132]
 [0.20702037]
 [0.19702585]
 [0.1959186 ]
 [0.19171509]
 [0.19157529]
 [0.18680234]
 [0.18068266]
 [0.17578271]
 [0.17433213]
 [0.17057276]
 [0.17013834]
 [0.16882835]
 [0.16821328]
 [0.16557032]
 [0.16380511]
 [0.16153654]
 [0.15995471]
 [0.15885249]
 [0.15816924]
 [0.15792274]
 [0.15748204]
 [0.15679127]
 [0.15587361]
 [0.1555207 ]
 [0.15271384]
 [0.15207654]
 [0.1512138 ]
 [0.14953306]
 [0.14667888]
 [0.14477013]
 [0.1442995 ]
 [0.14400776]
 [0.13946721]
 [0.1394459 ]
 [0.13848811]
 [0.1347454 ]
 [0.13153791]
 [0.12947841]
 [0.12844856]
 [0.12828225]
 [0.12628768]
 [0.12627855]
 [0.12318408]
 [0.12257603]
 [0.12061287]
 [0.11833573]
 [0.11676151]
 [0.11639172]
 [0.11618602]
 [0.11563145]
 [0.11483456]
 [0.11459462]
 [0.1142138 ]
 [0.11377727]
 [0.11315817]
 [0.11297113]
 [0.11213745]
 [0.11188567]
 [0.11177272]
 [0.11163275]
 [0.1105786 ]
 [0.10

[[0.73402095]
 [0.69916457]
 [0.39060417]
 [0.2635639 ]
 [0.26152235]
 [0.24736229]
 [0.23522273]
 [0.22958297]
 [0.218425  ]
 [0.21016335]
 [0.20813419]
 [0.20573623]
 [0.19975351]
 [0.19754636]
 [0.19572869]
 [0.19177786]
 [0.18999998]
 [0.18677515]
 [0.18420537]
 [0.18094136]
 [0.17174241]
 [0.17141321]
 [0.1707432 ]
 [0.1705857 ]
 [0.16325712]
 [0.1625945 ]
 [0.16161764]
 [0.16017006]
 [0.15834716]
 [0.1581625 ]
 [0.15777083]
 [0.15624891]
 [0.15530378]
 [0.1548967 ]
 [0.15443258]
 [0.1536307 ]
 [0.15359846]
 [0.15015513]
 [0.14553465]
 [0.14373177]
 [0.14358737]
 [0.1433744 ]
 [0.14163652]
 [0.13946855]
 [0.13730934]
 [0.13598688]
 [0.1351137 ]
 [0.13243641]
 [0.13056634]
 [0.12837957]
 [0.12598288]
 [0.12555909]
 [0.1252933 ]
 [0.12262472]
 [0.12212337]
 [0.1202443 ]
 [0.11796322]
 [0.1173485 ]
 [0.11695775]
 [0.11679097]
 [0.11592088]
 [0.11386399]
 [0.11270076]
 [0.11170451]
 [0.11147036]
 [0.11139026]
 [0.11118434]
 [0.11107654]
 [0.1107889 ]
 [0.11045169]
 [0.10995015]
 [0.10

[[0.71836466]
 [0.7040654 ]
 [0.4069944 ]
 [0.38791415]
 [0.26188216]
 [0.25914538]
 [0.24182463]
 [0.23199585]
 [0.22529353]
 [0.21854535]
 [0.21698704]
 [0.20762669]
 [0.20616576]
 [0.2026814 ]
 [0.20009598]
 [0.19801849]
 [0.19796441]
 [0.18984947]
 [0.18833807]
 [0.18493293]
 [0.18102649]
 [0.17957087]
 [0.17858729]
 [0.17399468]
 [0.17279044]
 [0.16875534]
 [0.16859561]
 [0.1676089 ]
 [0.16674304]
 [0.15995117]
 [0.15948446]
 [0.15833129]
 [0.15708117]
 [0.15576936]
 [0.155103  ]
 [0.15213764]
 [0.15075012]
 [0.14982097]
 [0.1454597 ]
 [0.14449139]
 [0.14272471]
 [0.14089349]
 [0.13961333]
 [0.1383132 ]
 [0.13628149]
 [0.13530006]
 [0.13435683]
 [0.13293539]
 [0.13257179]
 [0.13196264]
 [0.13140655]
 [0.12939388]
 [0.12836671]
 [0.12824233]
 [0.12540045]
 [0.12503034]
 [0.12320121]
 [0.12319787]
 [0.12173126]
 [0.12040751]
 [0.11945005]
 [0.11850435]
 [0.11698229]
 [0.11461334]
 [0.11327238]
 [0.11261003]
 [0.11245933]
 [0.1124552 ]
 [0.11240048]
 [0.1111161 ]
 [0.11007149]
 [0.11

[[0.72868586]
 [0.6984137 ]
 [0.42155015]
 [0.3764506 ]
 [0.3011668 ]
 [0.27484342]
 [0.2513693 ]
 [0.24846324]
 [0.21731116]
 [0.21400298]
 [0.2096052 ]
 [0.20714204]
 [0.20116358]
 [0.1996142 ]
 [0.19532104]
 [0.19504263]
 [0.19331287]
 [0.19220793]
 [0.1845649 ]
 [0.18130435]
 [0.18087658]
 [0.17650801]
 [0.16911818]
 [0.16855226]
 [0.16734266]
 [0.1646623 ]
 [0.16378498]
 [0.15951934]
 [0.158116  ]
 [0.15339302]
 [0.15262581]
 [0.15157495]
 [0.15010786]
 [0.14980216]
 [0.14776334]
 [0.14729021]
 [0.14659683]
 [0.14657377]
 [0.14597684]
 [0.14288577]
 [0.14247763]
 [0.13991807]
 [0.13830377]
 [0.13764574]
 [0.13748334]
 [0.13729031]
 [0.13632753]
 [0.13487981]
 [0.132182  ]
 [0.13063002]
 [0.13021307]
 [0.12965728]
 [0.12806846]
 [0.12707993]
 [0.12665382]
 [0.12654792]
 [0.12361708]
 [0.12330946]
 [0.12320628]
 [0.12086724]
 [0.12071057]
 [0.12037689]
 [0.11992577]
 [0.11656214]
 [0.11493687]
 [0.11477964]
 [0.11392872]
 [0.11391298]
 [0.11342169]
 [0.11234667]
 [0.112247  ]
 [0.11

[[0.7180534 ]
 [0.7080569 ]
 [0.4106103 ]
 [0.30492425]
 [0.23951876]
 [0.23683241]
 [0.23043765]
 [0.22682399]
 [0.22210354]
 [0.21405159]
 [0.20646173]
 [0.20034602]
 [0.197153  ]
 [0.19628641]
 [0.19493364]
 [0.18904495]
 [0.1875387 ]
 [0.18677267]
 [0.1822836 ]
 [0.18169963]
 [0.17853929]
 [0.17764731]
 [0.1764262 ]
 [0.17125417]
 [0.17054628]
 [0.17050098]
 [0.16951835]
 [0.16891444]
 [0.162967  ]
 [0.16292498]
 [0.16057444]
 [0.1599912 ]
 [0.15923381]
 [0.15903251]
 [0.15754627]
 [0.15729158]
 [0.15490995]
 [0.1547415 ]
 [0.14999841]
 [0.14866252]
 [0.14781822]
 [0.14680724]
 [0.14481047]
 [0.14389816]
 [0.14374414]
 [0.14038827]
 [0.13994335]
 [0.13841441]
 [0.135237  ]
 [0.13406925]
 [0.13365516]
 [0.13281451]
 [0.13017815]
 [0.12881318]
 [0.12787443]
 [0.12667184]
 [0.12574306]
 [0.12537155]
 [0.1253484 ]
 [0.12253296]
 [0.12070049]
 [0.12020626]
 [0.11962846]
 [0.11841919]
 [0.11767859]
 [0.11752139]
 [0.11474381]
 [0.11421059]
 [0.11382565]
 [0.11360705]
 [0.11343028]
 [0.11

[[0.7237663 ]
 [0.70015925]
 [0.37277758]
 [0.2838085 ]
 [0.2492318 ]
 [0.23813023]
 [0.23739745]
 [0.22297455]
 [0.20845231]
 [0.19897069]
 [0.19877127]
 [0.19799016]
 [0.19532329]
 [0.19208632]
 [0.1910877 ]
 [0.1908511 ]
 [0.19038215]
 [0.19026077]
 [0.18883596]
 [0.18571049]
 [0.18229637]
 [0.17562097]
 [0.17423148]
 [0.16761765]
 [0.16716047]
 [0.16663639]
 [0.16520925]
 [0.16512841]
 [0.16473438]
 [0.16113578]
 [0.15925676]
 [0.15888852]
 [0.15518825]
 [0.15236714]
 [0.1519755 ]
 [0.15122469]
 [0.15111586]
 [0.14918259]
 [0.14778435]
 [0.14664951]
 [0.14531833]
 [0.14519314]
 [0.14168338]
 [0.14092498]
 [0.13816455]
 [0.13807355]
 [0.13742284]
 [0.13614267]
 [0.13591094]
 [0.13284698]
 [0.13183743]
 [0.13124183]
 [0.12939465]
 [0.12817486]
 [0.12743826]
 [0.1272207 ]
 [0.12662628]
 [0.12516701]
 [0.12314785]
 [0.12297338]
 [0.12214173]
 [0.12205009]
 [0.12130857]
 [0.11949252]
 [0.1193361 ]
 [0.11911248]
 [0.1174676 ]
 [0.11744209]
 [0.11586971]
 [0.11574832]
 [0.11388783]
 [0.11

[[0.7068605 ]
 [0.7025911 ]
 [0.31891495]
 [0.30142835]
 [0.2862665 ]
 [0.26758552]
 [0.25129047]
 [0.23080252]
 [0.22347271]
 [0.20782639]
 [0.19380835]
 [0.18232602]
 [0.17811774]
 [0.17500512]
 [0.17239557]
 [0.16576941]
 [0.16374348]
 [0.16206199]
 [0.15863477]
 [0.1575418 ]
 [0.15539834]
 [0.15483704]
 [0.15415199]
 [0.15399753]
 [0.15367356]
 [0.15366597]
 [0.15201384]
 [0.15168153]
 [0.14944538]
 [0.14938942]
 [0.14893608]
 [0.14598642]
 [0.14093348]
 [0.13839048]
 [0.13808443]
 [0.13673025]
 [0.13438971]
 [0.13333166]
 [0.12935789]
 [0.12812074]
 [0.12567867]
 [0.12377965]
 [0.12362516]
 [0.12141474]
 [0.12086983]
 [0.12050929]
 [0.11859939]
 [0.1184831 ]
 [0.11680382]
 [0.11617478]
 [0.11610091]
 [0.11589436]
 [0.11493982]
 [0.11356346]
 [0.11275347]
 [0.11093787]
 [0.10854725]
 [0.1085117 ]
 [0.10811418]
 [0.1076597 ]
 [0.10615936]
 [0.10567813]
 [0.10550054]
 [0.10546812]
 [0.10515603]
 [0.10479182]
 [0.10366213]
 [0.10336502]
 [0.10249288]
 [0.10116654]
 [0.10016669]
 [0.10

[[0.7501457 ]
 [0.6979841 ]
 [0.28518414]
 [0.23833726]
 [0.22837602]
 [0.22745505]
 [0.20753878]
 [0.20406973]
 [0.20036861]
 [0.19915338]
 [0.19830959]
 [0.19353762]
 [0.19312443]
 [0.19302118]
 [0.18842389]
 [0.1835507 ]
 [0.178184  ]
 [0.17649801]
 [0.17133175]
 [0.16826782]
 [0.16482936]
 [0.1626049 ]
 [0.16257015]
 [0.16104229]
 [0.15341504]
 [0.15278889]
 [0.1526612 ]
 [0.1526474 ]
 [0.1525143 ]
 [0.1524757 ]
 [0.1522552 ]
 [0.15154292]
 [0.15090974]
 [0.14796749]
 [0.14322995]
 [0.14265242]
 [0.1417736 ]
 [0.14147615]
 [0.14020362]
 [0.13916387]
 [0.13793226]
 [0.13695942]
 [0.13408488]
 [0.13375546]
 [0.13186902]
 [0.1280873 ]
 [0.12751015]
 [0.12659177]
 [0.1259017 ]
 [0.12146626]
 [0.12015529]
 [0.11891521]
 [0.11862694]
 [0.11743061]
 [0.11702614]
 [0.11562905]
 [0.11480416]
 [0.11238328]
 [0.11047237]
 [0.11045424]
 [0.1104404 ]
 [0.10874058]
 [0.10872957]
 [0.10840312]
 [0.10825659]
 [0.10823228]
 [0.10811178]
 [0.10754283]
 [0.10692323]
 [0.10691558]
 [0.10654977]
 [0.10

[[0.732859  ]
 [0.70217305]
 [0.32462364]
 [0.268831  ]
 [0.26772603]
 [0.26421526]
 [0.25711903]
 [0.21962929]
 [0.19817278]
 [0.19389206]
 [0.19319172]
 [0.19235674]
 [0.18966651]
 [0.1895285 ]
 [0.18887293]
 [0.18694481]
 [0.18603128]
 [0.18277535]
 [0.1826819 ]
 [0.17834015]
 [0.17535964]
 [0.1715289 ]
 [0.16896227]
 [0.16853692]
 [0.16655171]
 [0.16480339]
 [0.16344322]
 [0.16339728]
 [0.16123055]
 [0.16062783]
 [0.15949053]
 [0.15883732]
 [0.15827794]
 [0.15483743]
 [0.15483037]
 [0.15202124]
 [0.14983973]
 [0.14979918]
 [0.14856902]
 [0.1465371 ]
 [0.14621137]
 [0.14403613]
 [0.14159054]
 [0.14059927]
 [0.13803077]
 [0.1379914 ]
 [0.13680951]
 [0.13551514]
 [0.13519879]
 [0.13408536]
 [0.13129854]
 [0.12969437]
 [0.12954926]
 [0.12519917]
 [0.12443642]
 [0.12439282]
 [0.12394893]
 [0.1220983 ]
 [0.12122322]
 [0.12121563]
 [0.11931048]
 [0.118714  ]
 [0.11865917]
 [0.11737824]
 [0.11697682]
 [0.11688121]
 [0.11432357]
 [0.11277628]
 [0.1121745 ]
 [0.11117635]
 [0.11064202]
 [0.11

[[0.7331621 ]
 [0.6961153 ]
 [0.46892065]
 [0.3377634 ]
 [0.3146204 ]
 [0.28052858]
 [0.2800152 ]
 [0.27240375]
 [0.24052384]
 [0.21393238]
 [0.21290468]
 [0.21102299]
 [0.20238638]
 [0.19839704]
 [0.19772398]
 [0.19749632]
 [0.19428375]
 [0.19359125]
 [0.19144218]
 [0.18945873]
 [0.18720889]
 [0.18314482]
 [0.1829943 ]
 [0.18170942]
 [0.18062726]
 [0.17922333]
 [0.17850544]
 [0.17815371]
 [0.1764189 ]
 [0.174551  ]
 [0.17268664]
 [0.17234054]
 [0.17164297]
 [0.1706031 ]
 [0.17003794]
 [0.1671226 ]
 [0.16709417]
 [0.16407873]
 [0.16281499]
 [0.16054958]
 [0.15808593]
 [0.15450066]
 [0.15331575]
 [0.15187863]
 [0.1506771 ]
 [0.14895901]
 [0.14778914]
 [0.14706013]
 [0.14249855]
 [0.14184235]
 [0.13432953]
 [0.13388264]
 [0.13160689]
 [0.13106923]
 [0.13082822]
 [0.12881327]
 [0.12856248]
 [0.12833475]
 [0.12729707]
 [0.12709685]
 [0.12637642]
 [0.12442677]
 [0.12409157]
 [0.12322231]
 [0.12171616]
 [0.12148006]
 [0.12028795]
 [0.11942439]
 [0.1192347 ]
 [0.11794244]
 [0.11789735]
 [0.11