In [1]:
import cv2
import numpy as np

In [2]:
# read class name from file

class_name = []
class_file = "../models/ssd_mobilenet_v3/coco.names"
with open(class_file, 'rt') as f:
    class_name = f.read().rstrip("\n").split("\n")
print(class_name[76])

cell phone


In [3]:
# load config and weight and instantiate the model

config = "../models/ssd_mobilenet_v3/ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt"
weights = "../models/ssd_mobilenet_v3/frozen_inference_graph.pb"

net = cv2.dnn_DetectionModel(weights, config)

# configure input for pretrained mdoel
net.setInputSize(320, 320)
net.setInputScale(1.0/127.5)
net.setInputMean((127.5, 127.5, 127.5))
net.setInputSwapRB(True)

<dnn_Model 0x7fbf396afe30>

In [124]:
cap.release()
cv2.destroyAllWindows()

In [127]:
#cap = cv2.VideoCapture("../media/video/face_elena.mp4")
cap = cv2.VideoCapture(1)
cap.set(3, 640)
cap.set(4, 480)

while cap.isOpened():
    ret, frame = cap.read()
    frame = cv2.resize(frame, (640, 480))
    #frame = cv2.flip(frame, 0)
    #frame = cv2.flip(frame, 1)
    
    # get detection
    class_ids, conf, bbox = net.detect(frame, confThreshold=0.1)
    
    test_list = list(zip(class_ids.flatten(), conf.flatten(), bbox))
    if test_list[0][0] == 77:
        phone_box = test_list[0][2]
        #print(phone_box)
        print(conf)
        cv2.rectangle(frame, phone_box, (0, 255, 0), 2)
        cv2.putText(frame, "CELL PHONE", (phone_box[0] + 10, phone_box[1] - 10),
                           cv2.FONT_HERSHEY_PLAIN, 1, (0, 255, 0), 2)
        #indices = cv2.dnn.NMSBoxes(phone_box, conf, 0.5, 0.5)
#    for class_id in class_ids:
#         if class_id == 77:
#             indices = cv2.dnn.NMSBoxes(list(bbox), conf, 0.5, 0.5)
#             print(indices)
#             if class_id == 77:
#                 indices = cv2.dnn.NMSBoxes(list(bbox), conf, 0.5, 0.5)
#                 for i in indices:
#                     i = i[0]
#                     box = bbox[i]
#                     x, y, w, h = box[0], box[1], box[2], box[3]
#                     cv2.rectangle(frame, (x,y), (x+w, y+h), (0, 255, 0), 2)
#                     cv2.putText(frame, class_name[class_ids[i][0] - 1].upper(), (box[0] + 10, box[1] + 30),
#                                         cv2.FONT_HERSHEY_PLAIN, 1, (0, 255, 0), 2)
    
#     for class_id, confidence, box in zip(class_ids.flatten(), conf.flatten(), bbox):
#     #for class_id in class_ids:
#         if class_id == 77:
#             bbox = list(bbox)
#             conf = list(np.array(conf).reshape(1, -1)[0])
#             conf = list(map(float, conf))
            
#             indices = cv2.dnn.NMSBoxes(bbox, conf, 0.5, 0,5)

#         for i in indices:
#             i = i[0]
#             box = box[i]
#             x, y, w, h = box[0], box[1], box[2], box[3]
#             cv2.rectangle(frame, (x,y), (x+w, y+h), (0, 255, 0), 2)
#             cv2.putText(frame, class_name[class_ids[i][0] - 1].upper(), (box[0] + 10, box[1] + 30),
#                                 cv2.FONT_HERSHEY_PLAIN, 1, (0, 255, 0), 2)
    # put boxes and prediction if there is detection
#     if len(class_ids) != 0:
#         for class_id, confidence, box in zip(class_ids.flatten(), conf.flatten(), bbox):
#             bbox = list(bbox)
#             conf = list(np.array(conf).reshape(1, -1)[0])
#             conf = list(map(float, conf))
#             if class_id == 77:
#                 indices = cv2.dnn.NMSBoxes(bbox, conf, 0.5, 0,5)
#                 print(indices)
#             for i in indices:
#                 i = i[0]
#                 #box = box[i]
#                 #print(type(box))
#                 x, y, w, h = box[0], box[1], box[2], box[3]
#                 cv2.rectangle(frame, (x,y), (x+w, y+h), (0, 255, 0), 2)
#                 cv2.putText(frame, class_name[class_ids[i][0] - 1].upper(), (box[0] + 10, box[1] + 30),
#                                     cv2.FONT_HERSHEY_PLAIN, 1, (0, 255, 0), 2)
                
#                 cv2.rectangle(frame, box, (0, 255, 0), 2)
#                 cv2.putText(frame, class_name[class_id - 1].upper(), (box[0] + 10, box[1] + 30),
#                            cv2.FONT_HERSHEY_PLAIN, 1, (0, 255, 0), 2)

    cv2.imshow('test',frame)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
            break
cap.release()
cv2.destroyAllWindows()

[[0.70872706]
 [0.7070275 ]
 [0.50592864]
 [0.4930889 ]
 [0.48643282]
 [0.4585329 ]
 [0.42161462]
 [0.41578776]
 [0.38624611]
 [0.3662131 ]
 [0.34640697]
 [0.33320555]
 [0.30383143]
 [0.2896326 ]
 [0.27943015]
 [0.27823928]
 [0.2752104 ]
 [0.2694158 ]
 [0.26760474]
 [0.2463117 ]
 [0.23874186]
 [0.23408525]
 [0.2337564 ]
 [0.22325611]
 [0.21748318]
 [0.21624076]
 [0.20749472]
 [0.2072091 ]
 [0.19453448]
 [0.19364701]
 [0.18891348]
 [0.18736398]
 [0.18624239]
 [0.18620373]
 [0.18089677]
 [0.18048604]
 [0.17833048]
 [0.17508574]
 [0.17256334]
 [0.16955572]
 [0.168647  ]
 [0.16764534]
 [0.16742735]
 [0.16645658]
 [0.16645037]
 [0.16584536]
 [0.1656362 ]
 [0.16142009]
 [0.1604483 ]
 [0.15656532]
 [0.15518986]
 [0.15497416]
 [0.15487191]
 [0.1542561 ]
 [0.15366067]
 [0.15351647]
 [0.152803  ]
 [0.15206492]
 [0.1514894 ]
 [0.1510058 ]
 [0.15012363]
 [0.1485259 ]
 [0.14817505]
 [0.1471995 ]
 [0.14710188]
 [0.14672789]
 [0.14404856]
 [0.14384322]
 [0.14216651]
 [0.14208841]
 [0.14179492]
 [0.14

[[0.7700249 ]
 [0.7129289 ]
 [0.2987684 ]
 [0.2975372 ]
 [0.29478875]
 [0.2934561 ]
 [0.29332456]
 [0.28375793]
 [0.2809231 ]
 [0.27605534]
 [0.25482532]
 [0.25363055]
 [0.24407071]
 [0.23928109]
 [0.23196708]
 [0.22249882]
 [0.2213075 ]
 [0.21582441]
 [0.21115983]
 [0.20840064]
 [0.20824586]
 [0.20729177]
 [0.1957583 ]
 [0.19279648]
 [0.18901753]
 [0.18487981]
 [0.17833722]
 [0.17446573]
 [0.17266423]
 [0.17205845]
 [0.17127989]
 [0.16955146]
 [0.1693897 ]
 [0.1693056 ]
 [0.16928181]
 [0.16926906]
 [0.16869633]
 [0.16739708]
 [0.16583288]
 [0.1599485 ]
 [0.15962668]
 [0.15712975]
 [0.15484565]
 [0.15260282]
 [0.15119784]
 [0.14995691]
 [0.14917648]
 [0.1469722 ]
 [0.14683534]
 [0.14673313]
 [0.14522208]
 [0.14139363]
 [0.14089862]
 [0.13851936]
 [0.13658677]
 [0.13396844]
 [0.1325871 ]
 [0.13144854]
 [0.1303746 ]
 [0.1301205 ]
 [0.12830964]
 [0.12758808]
 [0.12693042]
 [0.12628278]
 [0.12488535]
 [0.12474764]
 [0.12458265]
 [0.1234163 ]
 [0.12283468]
 [0.12183674]
 [0.12153015]
 [0.12

[[0.74284774]
 [0.70397544]
 [0.36456585]
 [0.34328848]
 [0.33174253]
 [0.32181692]
 [0.2980613 ]
 [0.29208574]
 [0.2740249 ]
 [0.2607212 ]
 [0.25543645]
 [0.25063357]
 [0.2502625 ]
 [0.24899383]
 [0.229847  ]
 [0.22889498]
 [0.22621174]
 [0.22308718]
 [0.20910597]
 [0.20597692]
 [0.19640264]
 [0.19560026]
 [0.19456102]
 [0.19405171]
 [0.19276811]
 [0.19105922]
 [0.1875757 ]
 [0.18728907]
 [0.18708475]
 [0.18434809]
 [0.18401067]
 [0.1805816 ]
 [0.17973474]
 [0.16918804]
 [0.16707343]
 [0.16599491]
 [0.16569869]
 [0.16469899]
 [0.1612875 ]
 [0.16034366]
 [0.15941262]
 [0.15913896]
 [0.15639272]
 [0.15056078]
 [0.15043649]
 [0.14900135]
 [0.14692615]
 [0.14418249]
 [0.13835384]
 [0.13760304]
 [0.13733642]
 [0.13727048]
 [0.1343599 ]
 [0.13259253]
 [0.13230692]
 [0.13184936]
 [0.13119557]
 [0.12983327]
 [0.12702674]
 [0.12701587]
 [0.12646873]
 [0.12616938]
 [0.12557904]
 [0.12450568]
 [0.12425756]
 [0.12403362]
 [0.12335286]
 [0.1224608 ]
 [0.12107099]
 [0.11947843]
 [0.11912252]
 [0.11

[[0.73998976]
 [0.6998338 ]
 [0.34592935]
 [0.33472565]
 [0.33358565]
 [0.32667118]
 [0.3072887 ]
 [0.3071215 ]
 [0.27134034]
 [0.26596674]
 [0.26269367]
 [0.25957987]
 [0.25397235]
 [0.24547787]
 [0.2388354 ]
 [0.2351003 ]
 [0.23347159]
 [0.23346233]
 [0.23321901]
 [0.22830354]
 [0.2273413 ]
 [0.22499962]
 [0.21990931]
 [0.21373591]
 [0.20788406]
 [0.20722678]
 [0.20709732]
 [0.20623727]
 [0.20409651]
 [0.19995686]
 [0.1988903 ]
 [0.19845587]
 [0.19130637]
 [0.19095442]
 [0.18436126]
 [0.17943557]
 [0.17569411]
 [0.17533894]
 [0.17472778]
 [0.17412692]
 [0.17304748]
 [0.16929531]
 [0.16656086]
 [0.16617528]
 [0.16595636]
 [0.16339643]
 [0.16242416]
 [0.16142978]
 [0.1565877 ]
 [0.1540086 ]
 [0.15353142]
 [0.15218087]
 [0.15041892]
 [0.14924717]
 [0.14850886]
 [0.14820102]
 [0.14710833]
 [0.14507015]
 [0.14307427]
 [0.14235748]
 [0.1413231 ]
 [0.14036556]
 [0.1384674 ]
 [0.13602355]
 [0.13600607]
 [0.13598141]
 [0.13534686]
 [0.13464564]
 [0.13227853]
 [0.13100307]
 [0.12928931]
 [0.12

[[0.77266103]
 [0.7169742 ]
 [0.5378253 ]
 [0.40857187]
 [0.39283907]
 [0.3860269 ]
 [0.34671205]
 [0.32960132]
 [0.32427105]
 [0.30330825]
 [0.27578256]
 [0.26863036]
 [0.26578715]
 [0.2568836 ]
 [0.25094277]
 [0.24246858]
 [0.24015015]
 [0.23078819]
 [0.22780016]
 [0.220863  ]
 [0.21755415]
 [0.21419798]
 [0.21397284]
 [0.20776145]
 [0.19865976]
 [0.19778885]
 [0.19614272]
 [0.19606969]
 [0.19507891]
 [0.18926789]
 [0.18680453]
 [0.18449667]
 [0.18119872]
 [0.18051744]
 [0.17795737]
 [0.17605065]
 [0.17385446]
 [0.16464618]
 [0.16368009]
 [0.16058785]
 [0.15419362]
 [0.15412799]
 [0.15291506]
 [0.15180828]
 [0.14921743]
 [0.14894073]
 [0.1484072 ]
 [0.14815633]
 [0.14786513]
 [0.14730977]
 [0.14724971]
 [0.14414059]
 [0.14410457]
 [0.1422867 ]
 [0.14135163]
 [0.14117391]
 [0.13983916]
 [0.13637476]
 [0.13390581]
 [0.13381323]
 [0.1329626 ]
 [0.13141222]
 [0.13092035]
 [0.13083142]
 [0.13065434]
 [0.13048199]
 [0.12946957]
 [0.1291888 ]
 [0.12908055]
 [0.12849714]
 [0.12817028]
 [0.12

[[0.72900677]
 [0.7179324 ]
 [0.46566936]
 [0.38340858]
 [0.36526865]
 [0.3468096 ]
 [0.33631074]
 [0.3339345 ]
 [0.31146324]
 [0.30892953]
 [0.30642277]
 [0.29814565]
 [0.29408258]
 [0.28400305]
 [0.28325343]
 [0.26015478]
 [0.25286028]
 [0.24721785]
 [0.24335831]
 [0.23740928]
 [0.23727964]
 [0.23422816]
 [0.23322378]
 [0.22954057]
 [0.22555964]
 [0.22474074]
 [0.21379605]
 [0.21229832]
 [0.20810796]
 [0.20738812]
 [0.2051557 ]
 [0.20480308]
 [0.2024845 ]
 [0.19301303]
 [0.19096856]
 [0.18824352]
 [0.18581288]
 [0.1833932 ]
 [0.1822372 ]
 [0.1798743 ]
 [0.17757495]
 [0.17531052]
 [0.17349741]
 [0.16864273]
 [0.16617699]
 [0.16417682]
 [0.16387212]
 [0.16330667]
 [0.15888649]
 [0.15725295]
 [0.15625428]
 [0.15334834]
 [0.15161337]
 [0.14922322]
 [0.14800596]
 [0.14728549]
 [0.14683741]
 [0.14678116]
 [0.1451074 ]
 [0.14482288]
 [0.14455427]
 [0.1422141 ]
 [0.14212349]
 [0.14178632]
 [0.14063405]
 [0.13950902]
 [0.13616116]
 [0.13556424]
 [0.13507526]
 [0.1338286 ]
 [0.13375291]
 [0.13

[[0.7451143 ]
 [0.7147237 ]
 [0.4026375 ]
 [0.37724832]
 [0.37345198]
 [0.36132267]
 [0.35401496]
 [0.31931555]
 [0.30741397]
 [0.3026527 ]
 [0.29888618]
 [0.2627364 ]
 [0.25959647]
 [0.25792307]
 [0.24838999]
 [0.24201705]
 [0.23412006]
 [0.23131636]
 [0.23096897]
 [0.22559303]
 [0.22284874]
 [0.2202191 ]
 [0.21907496]
 [0.21390526]
 [0.20796946]
 [0.2070227 ]
 [0.2034772 ]
 [0.19990966]
 [0.19942544]
 [0.1953017 ]
 [0.1874242 ]
 [0.18712145]
 [0.18127465]
 [0.17933263]
 [0.17900613]
 [0.17895369]
 [0.17869593]
 [0.173687  ]
 [0.16654375]
 [0.16400869]
 [0.15922034]
 [0.15619506]
 [0.15516292]
 [0.15449014]
 [0.1518942 ]
 [0.1517662 ]
 [0.1504606 ]
 [0.14982149]
 [0.14952074]
 [0.14882712]
 [0.14738363]
 [0.14299177]
 [0.14202425]
 [0.13965969]
 [0.13918926]
 [0.13888486]
 [0.13874884]
 [0.13808931]
 [0.1376583 ]
 [0.13667601]
 [0.13626096]
 [0.13526995]
 [0.13267426]
 [0.13161169]
 [0.1309382 ]
 [0.13030371]
 [0.13018253]
 [0.128716  ]
 [0.12776485]
 [0.12731263]
 [0.127146  ]
 [0.12

[[0.748989  ]
 [0.7203029 ]
 [0.39064348]
 [0.37440014]
 [0.3547042 ]
 [0.35100606]
 [0.34608257]
 [0.33886537]
 [0.31956545]
 [0.31618792]
 [0.2783617 ]
 [0.2571072 ]
 [0.24887776]
 [0.24227366]
 [0.24064374]
 [0.23546553]
 [0.23065203]
 [0.22835122]
 [0.22548649]
 [0.22298765]
 [0.21827985]
 [0.21506605]
 [0.20212044]
 [0.2015566 ]
 [0.19674931]
 [0.19322495]
 [0.19009021]
 [0.18038441]
 [0.17803235]
 [0.17766894]
 [0.17485629]
 [0.1739679 ]
 [0.16694804]
 [0.16403006]
 [0.16351809]
 [0.16151811]
 [0.16028301]
 [0.15405719]
 [0.15357666]
 [0.14724554]
 [0.14602652]
 [0.14532602]
 [0.14503849]
 [0.14452386]
 [0.13776222]
 [0.1373372 ]
 [0.13699919]
 [0.1355916 ]
 [0.1353523 ]
 [0.1347195 ]
 [0.13382865]
 [0.13282143]
 [0.12987463]
 [0.12959847]
 [0.12847263]
 [0.12841593]
 [0.12708813]
 [0.12703799]
 [0.12662575]
 [0.12643823]
 [0.12566768]
 [0.12560983]
 [0.12542361]
 [0.1253544 ]
 [0.12148867]
 [0.12146623]
 [0.11951622]
 [0.11762651]
 [0.11687491]
 [0.11672703]
 [0.11672664]
 [0.11

[[0.76589966]
 [0.7045577 ]
 [0.4362316 ]
 [0.4230268 ]
 [0.3639082 ]
 [0.3528797 ]
 [0.34682488]
 [0.34463927]
 [0.34420046]
 [0.33860075]
 [0.28640783]
 [0.26018915]
 [0.25336835]
 [0.25053686]
 [0.24967147]
 [0.23402731]
 [0.22657971]
 [0.2251736 ]
 [0.21807447]
 [0.21696013]
 [0.21536703]
 [0.20819019]
 [0.20308945]
 [0.19991879]
 [0.19919227]
 [0.19623107]
 [0.19139513]
 [0.1904845 ]
 [0.18904181]
 [0.18776132]
 [0.1858631 ]
 [0.18341962]
 [0.18177475]
 [0.17873545]
 [0.17357904]
 [0.17091891]
 [0.16788678]
 [0.16480356]
 [0.16256146]
 [0.16186075]
 [0.15996237]
 [0.1595218 ]
 [0.15868354]
 [0.1576086 ]
 [0.15535584]
 [0.15139525]
 [0.14823955]
 [0.14712894]
 [0.14558378]
 [0.14298412]
 [0.14212474]
 [0.14174297]
 [0.14170334]
 [0.1416799 ]
 [0.13955794]
 [0.13422509]
 [0.1332541 ]
 [0.13304123]
 [0.13143988]
 [0.12991159]
 [0.12919663]
 [0.12831539]
 [0.12603627]
 [0.12525065]
 [0.12514226]
 [0.12444541]
 [0.12289307]
 [0.12200916]
 [0.12054504]
 [0.12044851]
 [0.1181997 ]
 [0.11

[[0.7217081 ]
 [0.70504874]
 [0.38689965]
 [0.36221227]
 [0.32626802]
 [0.3123642 ]
 [0.3111165 ]
 [0.29752725]
 [0.29577693]
 [0.29493487]
 [0.2632673 ]
 [0.25755033]
 [0.24668615]
 [0.24530187]
 [0.24450521]
 [0.23970038]
 [0.2207655 ]
 [0.2198544 ]
 [0.21971735]
 [0.21717297]
 [0.21620658]
 [0.21501084]
 [0.2094379 ]
 [0.20478508]
 [0.193506  ]
 [0.19244978]
 [0.19059798]
 [0.1902915 ]
 [0.18859297]
 [0.18659244]
 [0.18634512]
 [0.18417375]
 [0.18226287]
 [0.18086307]
 [0.17259565]
 [0.16949752]
 [0.16671593]
 [0.16411842]
 [0.16380315]
 [0.16360494]
 [0.16261226]
 [0.16028716]
 [0.15932442]
 [0.15357564]
 [0.1520692 ]
 [0.15060759]
 [0.14868118]
 [0.14775419]
 [0.14643933]
 [0.14604649]
 [0.14020506]
 [0.13978037]
 [0.13918966]
 [0.13806662]
 [0.13800862]
 [0.13736917]
 [0.13405164]
 [0.1340303 ]
 [0.13353226]
 [0.13310044]
 [0.13147478]
 [0.13090305]
 [0.12923533]
 [0.12842938]
 [0.12717226]
 [0.12527527]
 [0.12290511]
 [0.12166761]
 [0.12077472]
 [0.12021534]
 [0.11962871]
 [0.11

[[0.7430818 ]
 [0.6973936 ]
 [0.5145025 ]
 [0.40793207]
 [0.38756973]
 [0.33721718]
 [0.30798513]
 [0.29638693]
 [0.28855607]
 [0.27802944]
 [0.25390702]
 [0.24362497]
 [0.24360593]
 [0.2428049 ]
 [0.24134956]
 [0.23834428]
 [0.23757695]
 [0.23351802]
 [0.20184885]
 [0.20041855]
 [0.19743505]
 [0.1932952 ]
 [0.19242485]
 [0.1916474 ]
 [0.18983038]
 [0.18736708]
 [0.18611243]
 [0.17913285]
 [0.17382185]
 [0.17225838]
 [0.16650233]
 [0.16557352]
 [0.16396008]
 [0.16042891]
 [0.16013671]
 [0.15762337]
 [0.15688832]
 [0.15531076]
 [0.1549425 ]
 [0.15488161]
 [0.15468669]
 [0.15420474]
 [0.15321001]
 [0.15202996]
 [0.15036614]
 [0.14957431]
 [0.14584808]
 [0.1458083 ]
 [0.14510185]
 [0.14359261]
 [0.13970499]
 [0.13875234]
 [0.13854979]
 [0.13787699]
 [0.13216728]
 [0.13214324]
 [0.13211203]
 [0.1315404 ]
 [0.1303272 ]
 [0.12919313]
 [0.12858906]
 [0.12766317]
 [0.12714793]
 [0.1266621 ]
 [0.12558298]
 [0.12459603]
 [0.12370891]
 [0.12283758]
 [0.12267137]
 [0.11976898]
 [0.11725401]
 [0.11

[[0.7234287 ]
 [0.7135199 ]
 [0.3813535 ]
 [0.37801528]
 [0.3513161 ]
 [0.3499044 ]
 [0.33681008]
 [0.32020846]
 [0.31807005]
 [0.29078963]
 [0.28671855]
 [0.26979885]
 [0.2658251 ]
 [0.26551518]
 [0.26497847]
 [0.25923744]
 [0.23665656]
 [0.23657393]
 [0.2357081 ]
 [0.2345616 ]
 [0.2229292 ]
 [0.22265166]
 [0.22174805]
 [0.21887311]
 [0.21292822]
 [0.20768374]
 [0.20506218]
 [0.198012  ]
 [0.19146556]
 [0.1912755 ]
 [0.18987776]
 [0.18874407]
 [0.18781237]
 [0.18440692]
 [0.18261908]
 [0.18252164]
 [0.18244255]
 [0.17612779]
 [0.1650544 ]
 [0.16449057]
 [0.16395037]
 [0.16368786]
 [0.15406343]
 [0.15199201]
 [0.14807867]
 [0.14661017]
 [0.14555147]
 [0.14331241]
 [0.14154765]
 [0.14129022]
 [0.1402923 ]
 [0.14024073]
 [0.13987274]
 [0.13927941]
 [0.13722716]
 [0.13401252]
 [0.13366708]
 [0.13362698]
 [0.1318234 ]
 [0.13149212]
 [0.13135144]
 [0.13113011]
 [0.1308977 ]
 [0.1307052 ]
 [0.13039654]
 [0.12953664]
 [0.12940353]
 [0.12903567]
 [0.12901585]
 [0.1286193 ]
 [0.12796184]
 [0.12

[[0.71722215]
 [0.7061466 ]
 [0.3959246 ]
 [0.39005518]
 [0.3675291 ]
 [0.3492215 ]
 [0.33568552]
 [0.32860655]
 [0.31832153]
 [0.29776114]
 [0.27925462]
 [0.27658865]
 [0.27332872]
 [0.24904162]
 [0.24877496]
 [0.24038085]
 [0.23817126]
 [0.23295596]
 [0.22701392]
 [0.22222523]
 [0.2217269 ]
 [0.21949084]
 [0.21934354]
 [0.21281752]
 [0.21062836]
 [0.20680447]
 [0.20464922]
 [0.20137921]
 [0.19598211]
 [0.19475618]
 [0.19342136]
 [0.1912766 ]
 [0.19073755]
 [0.18989153]
 [0.17895195]
 [0.17453125]
 [0.17368466]
 [0.1734987 ]
 [0.17138666]
 [0.17109175]
 [0.17079814]
 [0.16940485]
 [0.16677722]
 [0.1648565 ]
 [0.16027988]
 [0.15896696]
 [0.15698572]
 [0.15406689]
 [0.15320936]
 [0.15291776]
 [0.14990842]
 [0.14884341]
 [0.14698225]
 [0.1466238 ]
 [0.14400348]
 [0.14122935]
 [0.1411322 ]
 [0.14077482]
 [0.14047664]
 [0.13763264]
 [0.1364379 ]
 [0.1330401 ]
 [0.13109654]
 [0.13077375]
 [0.13048165]
 [0.12984458]
 [0.12964168]
 [0.12893468]
 [0.12836179]
 [0.12745084]
 [0.12669866]
 [0.12

[[0.7399539 ]
 [0.7094061 ]
 [0.45028898]
 [0.41730055]
 [0.4106863 ]
 [0.39742872]
 [0.35542157]
 [0.34470752]
 [0.32230714]
 [0.3211572 ]
 [0.31655604]
 [0.29795912]
 [0.28364006]
 [0.2584511 ]
 [0.25677767]
 [0.24557608]
 [0.23228632]
 [0.22632545]
 [0.22598104]
 [0.22361708]
 [0.21766245]
 [0.2170494 ]
 [0.21479514]
 [0.21472956]
 [0.21387808]
 [0.21043599]
 [0.20416808]
 [0.20061041]
 [0.1994859 ]
 [0.1989753 ]
 [0.19811043]
 [0.19711852]
 [0.18774529]
 [0.18647307]
 [0.1845989 ]
 [0.18356007]
 [0.17046024]
 [0.17025588]
 [0.16781294]
 [0.16217035]
 [0.1586869 ]
 [0.15582372]
 [0.15548043]
 [0.15425998]
 [0.15214849]
 [0.15101247]
 [0.14957766]
 [0.14590761]
 [0.14586829]
 [0.14431614]
 [0.14285266]
 [0.1425975 ]
 [0.14157161]
 [0.14053252]
 [0.13835931]
 [0.13642217]
 [0.13566169]
 [0.13538146]
 [0.13510492]
 [0.13477287]
 [0.13407718]
 [0.1337106 ]
 [0.13213849]
 [0.13172926]
 [0.1311669 ]
 [0.13022079]
 [0.12962225]
 [0.12950861]
 [0.12940873]
 [0.12938194]
 [0.12890135]
 [0.12

[[0.74291456]
 [0.70570797]
 [0.3148014 ]
 [0.29465777]
 [0.28987747]
 [0.2855202 ]
 [0.24475682]
 [0.24018459]
 [0.22747415]
 [0.22482762]
 [0.22433925]
 [0.22124904]
 [0.21710601]
 [0.20533907]
 [0.19698901]
 [0.19641644]
 [0.19241486]
 [0.18934986]
 [0.18742397]
 [0.1867332 ]
 [0.1834373 ]
 [0.18128473]
 [0.17893067]
 [0.17221943]
 [0.17169021]
 [0.16669151]
 [0.16244277]
 [0.16203004]
 [0.16164121]
 [0.16001908]
 [0.15926799]
 [0.15821767]
 [0.1568419 ]
 [0.156294  ]
 [0.15365778]
 [0.15314949]
 [0.15102166]
 [0.15092668]
 [0.15058026]
 [0.1477898 ]
 [0.1452683 ]
 [0.14371951]
 [0.14297967]
 [0.14082298]
 [0.13946824]
 [0.13559335]
 [0.13453159]
 [0.13307087]
 [0.13283712]
 [0.1323715 ]
 [0.13037951]
 [0.12807666]
 [0.12797368]
 [0.12731314]
 [0.12722187]
 [0.12637456]
 [0.12474393]
 [0.12423547]
 [0.12333063]
 [0.11953969]
 [0.11784811]
 [0.11687475]
 [0.11634313]
 [0.11542746]
 [0.11332931]
 [0.11254361]
 [0.1122242 ]
 [0.11183152]
 [0.11056416]
 [0.1101283 ]
 [0.10943279]
 [0.10

[[0.79939246]
 [0.7003552 ]
 [0.35168493]
 [0.34156755]
 [0.30752984]
 [0.30275777]
 [0.27940005]
 [0.25821304]
 [0.24870521]
 [0.24551539]
 [0.24350005]
 [0.24219707]
 [0.24049224]
 [0.24029785]
 [0.23171444]
 [0.22529246]
 [0.21712701]
 [0.20849812]
 [0.20585105]
 [0.20551284]
 [0.19803512]
 [0.19662228]
 [0.19159803]
 [0.1877865 ]
 [0.18541099]
 [0.18359302]
 [0.18149817]
 [0.1794947 ]
 [0.17833726]
 [0.1741178 ]
 [0.17214133]
 [0.17092794]
 [0.17026095]
 [0.16882788]
 [0.16837995]
 [0.16645716]
 [0.16572182]
 [0.16560681]
 [0.1646969 ]
 [0.16442466]
 [0.16355257]
 [0.15994015]
 [0.15958281]
 [0.15776551]
 [0.15744586]
 [0.15662543]
 [0.15544158]
 [0.15530047]
 [0.15508047]
 [0.15461645]
 [0.15328158]
 [0.15236084]
 [0.15140948]
 [0.1502768 ]
 [0.14914592]
 [0.14880528]
 [0.14705068]
 [0.14494042]
 [0.14234178]
 [0.13946238]
 [0.13895953]
 [0.13837467]
 [0.13830471]
 [0.13672844]
 [0.13622428]
 [0.13497858]
 [0.13354759]
 [0.13156343]
 [0.13129608]
 [0.131294  ]
 [0.13102967]
 [0.12

[[0.79510105]
 [0.69989204]
 [0.37400028]
 [0.35163912]
 [0.3464546 ]
 [0.298783  ]
 [0.29376692]
 [0.28779733]
 [0.27967885]
 [0.2759506 ]
 [0.25955388]
 [0.25042084]
 [0.2466952 ]
 [0.23521991]
 [0.2328784 ]
 [0.23229337]
 [0.22288768]
 [0.21858107]
 [0.20922258]
 [0.2087356 ]
 [0.20608866]
 [0.20566365]
 [0.20112503]
 [0.19972923]
 [0.19542255]
 [0.19335294]
 [0.19236888]
 [0.190287  ]
 [0.18969879]
 [0.1887804 ]
 [0.18439542]
 [0.18226063]
 [0.1761889 ]
 [0.17444341]
 [0.17420001]
 [0.16572608]
 [0.16375042]
 [0.16103777]
 [0.16086628]
 [0.16038427]
 [0.159931  ]
 [0.1591756 ]
 [0.15895218]
 [0.1564596 ]
 [0.15601994]
 [0.15575983]
 [0.15501137]
 [0.15462872]
 [0.15378822]
 [0.15212739]
 [0.15042159]
 [0.14660695]
 [0.14498329]
 [0.14346766]
 [0.14325015]
 [0.14240918]
 [0.14038262]
 [0.138845  ]
 [0.13842957]
 [0.13723423]
 [0.13710757]
 [0.13596043]
 [0.13584074]
 [0.13376844]
 [0.13273211]
 [0.13268878]
 [0.13268858]
 [0.13242632]
 [0.13126303]
 [0.13023898]
 [0.12741297]
 [0.12

[[0.7216034 ]
 [0.7087197 ]
 [0.408202  ]
 [0.36243153]
 [0.35490757]
 [0.35438448]
 [0.34269762]
 [0.3266189 ]
 [0.3258766 ]
 [0.3078998 ]
 [0.29104027]
 [0.27243242]
 [0.26530847]
 [0.254237  ]
 [0.2430562 ]
 [0.24220927]
 [0.21247448]
 [0.20829901]
 [0.20708133]
 [0.20671755]
 [0.20475529]
 [0.19729413]
 [0.19442415]
 [0.18561089]
 [0.18194504]
 [0.18062256]
 [0.17306067]
 [0.1691491 ]
 [0.16753896]
 [0.16474408]
 [0.1634912 ]
 [0.15972902]
 [0.15808101]
 [0.1578659 ]
 [0.1568954 ]
 [0.1561816 ]
 [0.15592225]
 [0.1544236 ]
 [0.15389694]
 [0.15266804]
 [0.15230724]
 [0.15018062]
 [0.14885183]
 [0.14862284]
 [0.14710407]
 [0.14544469]
 [0.14475237]
 [0.14467739]
 [0.14338504]
 [0.14322382]
 [0.14266644]
 [0.14134167]
 [0.14125064]
 [0.13816133]
 [0.13748467]
 [0.13716279]
 [0.13568   ]
 [0.13413104]
 [0.13360865]
 [0.13271596]
 [0.13266817]
 [0.13211825]
 [0.1320884 ]
 [0.13162416]
 [0.13127576]
 [0.13119332]
 [0.128102  ]
 [0.12778492]
 [0.12715796]
 [0.12674426]
 [0.12530053]
 [0.12

[[0.7681726 ]
 [0.7094115 ]
 [0.43659568]
 [0.43028873]
 [0.42351225]
 [0.41531196]
 [0.3735233 ]
 [0.3568991 ]
 [0.32104474]
 [0.28801775]
 [0.28777367]
 [0.2687423 ]
 [0.26575002]
 [0.2517742 ]
 [0.25112462]
 [0.24400203]
 [0.2402383 ]
 [0.21995632]
 [0.2143565 ]
 [0.20530814]
 [0.20018002]
 [0.19569252]
 [0.19516405]
 [0.19242914]
 [0.19103059]
 [0.18856335]
 [0.18649472]
 [0.18368584]
 [0.18133512]
 [0.17680891]
 [0.1758845 ]
 [0.17352764]
 [0.17140606]
 [0.1697824 ]
 [0.16973455]
 [0.16890173]
 [0.16858265]
 [0.16755642]
 [0.16652827]
 [0.16512486]
 [0.16175702]
 [0.16053617]
 [0.1587112 ]
 [0.15710214]
 [0.15676849]
 [0.15049946]
 [0.14976695]
 [0.1491818 ]
 [0.14783938]
 [0.14762157]
 [0.14638923]
 [0.14346956]
 [0.14260742]
 [0.14208992]
 [0.14000773]
 [0.13955562]
 [0.13870631]
 [0.13782977]
 [0.1377302 ]
 [0.1346868 ]
 [0.13391748]
 [0.13128619]
 [0.13103199]
 [0.13028325]
 [0.12951814]
 [0.1285269 ]
 [0.12777704]
 [0.12596196]
 [0.1250562 ]
 [0.12409974]
 [0.12405586]
 [0.12

[[0.7184637 ]
 [0.71034455]
 [0.38430429]
 [0.3645568 ]
 [0.34464782]
 [0.34393585]
 [0.34133938]
 [0.33199003]
 [0.31603447]
 [0.3157009 ]
 [0.29802907]
 [0.27739364]
 [0.25802717]
 [0.2534824 ]
 [0.24860945]
 [0.24114451]
 [0.2220994 ]
 [0.22206347]
 [0.22147869]
 [0.21927163]
 [0.21624938]
 [0.20532294]
 [0.19505268]
 [0.19440506]
 [0.19396347]
 [0.19251385]
 [0.1887976 ]
 [0.18364489]
 [0.1814941 ]
 [0.17965129]
 [0.17929201]
 [0.17831379]
 [0.17750625]
 [0.17706619]
 [0.17423457]
 [0.17287971]
 [0.17210399]
 [0.16658284]
 [0.1657289 ]
 [0.16455182]
 [0.16252008]
 [0.15783335]
 [0.15732913]
 [0.15567718]
 [0.15497325]
 [0.14644803]
 [0.1429738 ]
 [0.14055294]
 [0.13967273]
 [0.13915835]
 [0.13755465]
 [0.1373721 ]
 [0.1372895 ]
 [0.13701192]
 [0.1369608 ]
 [0.13610323]
 [0.13351846]
 [0.13180785]
 [0.13167183]
 [0.13055126]
 [0.13036469]
 [0.1298107 ]
 [0.1297449 ]
 [0.12886764]
 [0.1278304 ]
 [0.12406871]
 [0.12391161]
 [0.12377491]
 [0.12375119]
 [0.1216187 ]
 [0.11907917]
 [0.11

[[0.71476716]
 [0.6917246 ]
 [0.44243395]
 [0.41253006]
 [0.35061514]
 [0.34897262]
 [0.3481492 ]
 [0.34174043]
 [0.341186  ]
 [0.3105151 ]
 [0.30758947]
 [0.30395046]
 [0.29062247]
 [0.28904116]
 [0.2887435 ]
 [0.25505495]
 [0.25461358]
 [0.25096872]
 [0.243299  ]
 [0.23465168]
 [0.22993594]
 [0.22225477]
 [0.22112608]
 [0.20923442]
 [0.20843726]
 [0.20626223]
 [0.20555212]
 [0.20474465]
 [0.20442222]
 [0.20399007]
 [0.20227802]
 [0.19509418]
 [0.19302255]
 [0.1928325 ]
 [0.18886018]
 [0.18743375]
 [0.17171036]
 [0.16435346]
 [0.16360207]
 [0.16357322]
 [0.16318993]
 [0.15955931]
 [0.1574891 ]
 [0.15512237]
 [0.154275  ]
 [0.15101826]
 [0.15100458]
 [0.15027107]
 [0.14884092]
 [0.14792925]
 [0.14633425]
 [0.14418744]
 [0.14327194]
 [0.14326094]
 [0.14168821]
 [0.14075013]
 [0.1399387 ]
 [0.13971992]
 [0.13873577]
 [0.1374322 ]
 [0.13671908]
 [0.13623872]
 [0.1347116 ]
 [0.13456775]
 [0.13387206]
 [0.13030568]
 [0.12983203]
 [0.12888089]
 [0.12885785]
 [0.12859687]
 [0.12828168]
 [0.12

[[0.72074366]
 [0.71206254]
 [0.4015394 ]
 [0.40102884]
 [0.36492756]
 [0.3599832 ]
 [0.3455642 ]
 [0.3379972 ]
 [0.32604232]
 [0.32371217]
 [0.31952247]
 [0.3171751 ]
 [0.31463817]
 [0.27679583]
 [0.27542904]
 [0.25729248]
 [0.2546524 ]
 [0.2529843 ]
 [0.25116998]
 [0.23125197]
 [0.22788453]
 [0.22066857]
 [0.21517448]
 [0.21420524]
 [0.21359028]
 [0.20796795]
 [0.2059323 ]
 [0.2050919 ]
 [0.19434321]
 [0.19143568]
 [0.18958196]
 [0.17909382]
 [0.17542641]
 [0.174902  ]
 [0.17261466]
 [0.17074163]
 [0.16959812]
 [0.16704182]
 [0.16578357]
 [0.16515608]
 [0.16459331]
 [0.16427809]
 [0.16139053]
 [0.16130184]
 [0.16127487]
 [0.15616968]
 [0.15583888]
 [0.1544255 ]
 [0.15073259]
 [0.15030476]
 [0.14991824]
 [0.14689204]
 [0.1449899 ]
 [0.14441656]
 [0.14349505]
 [0.14335948]
 [0.14246282]
 [0.14237973]
 [0.1380993 ]
 [0.13701607]
 [0.13658263]
 [0.13655819]
 [0.13524224]
 [0.1334139 ]
 [0.13252427]
 [0.13163309]
 [0.130143  ]
 [0.12994061]
 [0.129898  ]
 [0.12930666]
 [0.12908417]
 [0.12

[[0.7425707 ]
 [0.7041954 ]
 [0.5219242 ]
 [0.42271653]
 [0.3936993 ]
 [0.3863558 ]
 [0.38404664]
 [0.3813521 ]
 [0.37660074]
 [0.35271883]
 [0.34624907]
 [0.28782704]
 [0.24803519]
 [0.23870656]
 [0.2385547 ]
 [0.23731717]
 [0.23493394]
 [0.23025344]
 [0.22833869]
 [0.22814769]
 [0.2274338 ]
 [0.20966467]
 [0.2088387 ]
 [0.20604578]
 [0.20362836]
 [0.20124392]
 [0.20107621]
 [0.20002134]
 [0.19616058]
 [0.19527683]
 [0.19261621]
 [0.19046526]
 [0.18954255]
 [0.1861134 ]
 [0.1816947 ]
 [0.18065998]
 [0.18065725]
 [0.17993231]
 [0.17910972]
 [0.17178346]
 [0.17098853]
 [0.16935676]
 [0.16831727]
 [0.16474967]
 [0.16378647]
 [0.16287763]
 [0.16277735]
 [0.16203576]
 [0.16014388]
 [0.15708783]
 [0.156216  ]
 [0.14855556]
 [0.14803872]
 [0.14766236]
 [0.14560606]
 [0.1451174 ]
 [0.14465795]
 [0.14185604]
 [0.14185491]
 [0.14006558]
 [0.13814577]
 [0.1375525 ]
 [0.13495377]
 [0.13313715]
 [0.13152555]
 [0.1299381 ]
 [0.12831126]
 [0.1261069 ]
 [0.12571849]
 [0.12502876]
 [0.12371013]
 [0.12

[[0.7456239 ]
 [0.6957682 ]
 [0.573164  ]
 [0.43823716]
 [0.40314895]
 [0.39871067]
 [0.39282197]
 [0.38719803]
 [0.32646257]
 [0.3142656 ]
 [0.31239575]
 [0.3115397 ]
 [0.30667868]
 [0.25603938]
 [0.24194777]
 [0.23357628]
 [0.23347637]
 [0.23138697]
 [0.22892559]
 [0.21914707]
 [0.21615785]
 [0.21279861]
 [0.21123026]
 [0.20649976]
 [0.20400855]
 [0.20251088]
 [0.2003398 ]
 [0.19899742]
 [0.19853443]
 [0.19808228]
 [0.1976067 ]
 [0.19716217]
 [0.1917589 ]
 [0.18725032]
 [0.18460207]
 [0.18458036]
 [0.18246974]
 [0.17661688]
 [0.17533506]
 [0.17457391]
 [0.17210118]
 [0.17182986]
 [0.17139876]
 [0.16716182]
 [0.16411762]
 [0.16128372]
 [0.15708536]
 [0.15579179]
 [0.15471983]
 [0.15434462]
 [0.15434   ]
 [0.15213199]
 [0.14856087]
 [0.14620611]
 [0.14619021]
 [0.14433888]
 [0.14401202]
 [0.14338996]
 [0.14318441]
 [0.14085948]
 [0.1391473 ]
 [0.1372581 ]
 [0.1370638 ]
 [0.13682057]
 [0.135374  ]
 [0.1350106 ]
 [0.13478732]
 [0.13394296]
 [0.13373357]
 [0.13182038]
 [0.13119483]
 [0.13

[[0.75671   ]
 [0.6959624 ]
 [0.5047584 ]
 [0.40681088]
 [0.40252388]
 [0.3762547 ]
 [0.34010825]
 [0.3386807 ]
 [0.3233367 ]
 [0.31649002]
 [0.30196247]
 [0.25236422]
 [0.24234667]
 [0.23838338]
 [0.2310392 ]
 [0.22975919]
 [0.22100441]
 [0.21508254]
 [0.21236102]
 [0.21220492]
 [0.21159945]
 [0.20411418]
 [0.20051844]
 [0.19520408]
 [0.1944141 ]
 [0.19025767]
 [0.18236946]
 [0.17991877]
 [0.17827117]
 [0.1744302 ]
 [0.17274082]
 [0.17243427]
 [0.16850889]
 [0.16535918]
 [0.1647217 ]
 [0.16285364]
 [0.1621983 ]
 [0.15976849]
 [0.15962622]
 [0.15884697]
 [0.15513268]
 [0.1532547 ]
 [0.15280151]
 [0.15227427]
 [0.15058136]
 [0.15019645]
 [0.14901266]
 [0.14877516]
 [0.1471092 ]
 [0.14694919]
 [0.1451582 ]
 [0.14473331]
 [0.14359401]
 [0.14260106]
 [0.14146404]
 [0.13827422]
 [0.13814986]
 [0.13765846]
 [0.13764252]
 [0.13707292]
 [0.13689184]
 [0.13611168]
 [0.13522463]
 [0.13505584]
 [0.13409545]
 [0.13348119]
 [0.1330851 ]
 [0.13289271]
 [0.1327578 ]
 [0.13151194]
 [0.13081464]
 [0.13

[[0.75670135]
 [0.69503117]
 [0.5447077 ]
 [0.41986883]
 [0.4091908 ]
 [0.40491337]
 [0.37767318]
 [0.34098962]
 [0.32510698]
 [0.32139534]
 [0.31627536]
 [0.29142338]
 [0.2567104 ]
 [0.23535992]
 [0.23453556]
 [0.23295544]
 [0.2277036 ]
 [0.22500682]
 [0.22457983]
 [0.22389054]
 [0.21404275]
 [0.21190171]
 [0.21010834]
 [0.20823635]
 [0.2063198 ]
 [0.20094411]
 [0.19811924]
 [0.19553027]
 [0.19128048]
 [0.18958183]
 [0.18781982]
 [0.18739694]
 [0.18205068]
 [0.18186176]
 [0.1778701 ]
 [0.17489186]
 [0.17447507]
 [0.17200908]
 [0.17084232]
 [0.169486  ]
 [0.16754624]
 [0.16724318]
 [0.16563347]
 [0.16364571]
 [0.16221699]
 [0.16087778]
 [0.15917908]
 [0.15718785]
 [0.15533023]
 [0.15472108]
 [0.15107124]
 [0.14940487]
 [0.14904988]
 [0.14856702]
 [0.14715475]
 [0.14665867]
 [0.14639322]
 [0.14547664]
 [0.14491192]
 [0.144052  ]
 [0.14265326]
 [0.14087346]
 [0.14032714]
 [0.13882984]
 [0.13864696]
 [0.13663214]
 [0.13538985]
 [0.13351575]
 [0.13235928]
 [0.13048823]
 [0.1234355 ]
 [0.12

[[0.7353871 ]
 [0.69742846]
 [0.4640839 ]
 [0.46380392]
 [0.44855058]
 [0.3844738 ]
 [0.3603143 ]
 [0.33290383]
 [0.31411216]
 [0.30508018]
 [0.27743295]
 [0.2665866 ]
 [0.2598878 ]
 [0.24520333]
 [0.23606916]
 [0.230994  ]
 [0.22288683]
 [0.2185715 ]
 [0.21695903]
 [0.21445219]
 [0.21395802]
 [0.21375944]
 [0.20535977]
 [0.20173174]
 [0.19806272]
 [0.19763856]
 [0.19690888]
 [0.19632676]
 [0.19278982]
 [0.19210356]
 [0.18964781]
 [0.18910746]
 [0.18662663]
 [0.18622245]
 [0.185947  ]
 [0.18521325]
 [0.18078618]
 [0.1783813 ]
 [0.17759976]
 [0.17534958]
 [0.173685  ]
 [0.16855054]
 [0.1647717 ]
 [0.16468652]
 [0.16426635]
 [0.16425715]
 [0.16136535]
 [0.16109012]
 [0.15721454]
 [0.15511669]
 [0.15448156]
 [0.1542766 ]
 [0.1533043 ]
 [0.14591739]
 [0.14391197]
 [0.14340496]
 [0.14312704]
 [0.14054371]
 [0.13888533]
 [0.13884594]
 [0.13756543]
 [0.13556273]
 [0.13139622]
 [0.12997758]
 [0.12717253]
 [0.12625389]
 [0.12243867]
 [0.12106431]
 [0.12091178]
 [0.11866289]
 [0.11801751]
 [0.11

[[0.726256  ]
 [0.6953338 ]
 [0.5219322 ]
 [0.47758105]
 [0.47449353]
 [0.425865  ]
 [0.3548606 ]
 [0.35103485]
 [0.34863722]
 [0.3385544 ]
 [0.29652646]
 [0.2690704 ]
 [0.2671187 ]
 [0.25970224]
 [0.25311843]
 [0.24697928]
 [0.24529241]
 [0.21775284]
 [0.21590841]
 [0.20660082]
 [0.20364693]
 [0.19104008]
 [0.18983907]
 [0.18563464]
 [0.18470567]
 [0.18276575]
 [0.18202645]
 [0.18158327]
 [0.18151817]
 [0.17928258]
 [0.17859036]
 [0.17383045]
 [0.16917366]
 [0.16678484]
 [0.16620462]
 [0.16364391]
 [0.15836968]
 [0.15773813]
 [0.15673508]
 [0.15614736]
 [0.15329564]
 [0.15061411]
 [0.14994209]
 [0.14926928]
 [0.14795665]
 [0.1473143 ]
 [0.14704941]
 [0.14516918]
 [0.14187384]
 [0.13937226]
 [0.13845247]
 [0.13755453]
 [0.13707721]
 [0.13641134]
 [0.13601574]
 [0.13597724]
 [0.13509683]
 [0.13470198]
 [0.13351834]
 [0.13242815]
 [0.13206084]
 [0.13196729]
 [0.1314504 ]
 [0.1312153 ]
 [0.13074604]
 [0.13040535]
 [0.12998663]
 [0.12955129]
 [0.12871823]
 [0.12827791]
 [0.12802175]
 [0.12

[[0.74040836]
 [0.69782007]
 [0.53451896]
 [0.44930506]
 [0.43387875]
 [0.4198969 ]
 [0.35063022]
 [0.3411874 ]
 [0.33086947]
 [0.28662187]
 [0.2700984 ]
 [0.26108938]
 [0.2517487 ]
 [0.24976169]
 [0.24806443]
 [0.21369414]
 [0.21213894]
 [0.20299135]
 [0.19909966]
 [0.19817938]
 [0.19247611]
 [0.18792267]
 [0.18218334]
 [0.18210647]
 [0.17963123]
 [0.17310715]
 [0.1715584 ]
 [0.17151567]
 [0.16851059]
 [0.16678508]
 [0.16639122]
 [0.16638903]
 [0.16084826]
 [0.15837932]
 [0.15754654]
 [0.15734813]
 [0.15572144]
 [0.15432595]
 [0.15388812]
 [0.15373036]
 [0.15330294]
 [0.15248053]
 [0.14641818]
 [0.14626302]
 [0.14593013]
 [0.14455882]
 [0.14415987]
 [0.14334197]
 [0.13916321]
 [0.13859797]
 [0.1382727 ]
 [0.13776977]
 [0.13743612]
 [0.1365041 ]
 [0.13643827]
 [0.1346522 ]
 [0.13413154]
 [0.13035874]
 [0.12981413]
 [0.1287204 ]
 [0.12674385]
 [0.12490914]
 [0.12484825]
 [0.12422129]
 [0.12412377]
 [0.12320939]
 [0.12260471]
 [0.12250767]
 [0.12213632]
 [0.11966595]
 [0.11920071]
 [0.11

[[0.7423111 ]
 [0.69666106]
 [0.5273838 ]
 [0.45857802]
 [0.41292217]
 [0.36814755]
 [0.34934795]
 [0.32435   ]
 [0.3057455 ]
 [0.2642917 ]
 [0.25059548]
 [0.24797179]
 [0.2417075 ]
 [0.23990834]
 [0.23866606]
 [0.23167738]
 [0.2309638 ]
 [0.22391619]
 [0.2188425 ]
 [0.1923418 ]
 [0.18996814]
 [0.18810153]
 [0.18334283]
 [0.17669886]
 [0.17550874]
 [0.1726719 ]
 [0.17228498]
 [0.1712172 ]
 [0.16957788]
 [0.16800289]
 [0.16713005]
 [0.16407238]
 [0.16087355]
 [0.16035078]
 [0.1594293 ]
 [0.15894526]
 [0.15828127]
 [0.15822123]
 [0.15747815]
 [0.15596645]
 [0.15563644]
 [0.15155303]
 [0.14915235]
 [0.14816043]
 [0.14794537]
 [0.14499359]
 [0.14466998]
 [0.14383034]
 [0.1426639 ]
 [0.14118838]
 [0.13992852]
 [0.13922165]
 [0.13624884]
 [0.13566728]
 [0.13352758]
 [0.13284309]
 [0.13192575]
 [0.13130632]
 [0.13092841]
 [0.12811393]
 [0.12594011]
 [0.12483871]
 [0.12405377]
 [0.12281033]
 [0.12258665]
 [0.12251127]
 [0.12096813]
 [0.1185507 ]
 [0.11797363]
 [0.1174534 ]
 [0.11649677]
 [0.11

[[0.7429091 ]
 [0.7144472 ]
 [0.6316235 ]
 [0.62258106]
 [0.45673212]
 [0.35044765]
 [0.28483987]
 [0.2783076 ]
 [0.25206935]
 [0.24438645]
 [0.23939706]
 [0.23790315]
 [0.23785551]
 [0.23289345]
 [0.22732265]
 [0.2254832 ]
 [0.22380911]
 [0.22100504]
 [0.21945465]
 [0.21940298]
 [0.20425993]
 [0.19979157]
 [0.19973312]
 [0.19142875]
 [0.18759246]
 [0.18282595]
 [0.18161812]
 [0.18008657]
 [0.17677729]
 [0.1764371 ]
 [0.17601024]
 [0.17537743]
 [0.17527223]
 [0.16980769]
 [0.16976964]
 [0.16777295]
 [0.16718046]
 [0.16675787]
 [0.15924862]
 [0.15826768]
 [0.15707424]
 [0.15511198]
 [0.15458655]
 [0.15446152]
 [0.15290488]
 [0.15276009]
 [0.15267508]
 [0.15264663]
 [0.1519224 ]
 [0.15120333]
 [0.15087321]
 [0.15085521]
 [0.14885345]
 [0.14859413]
 [0.1483162 ]
 [0.1475858 ]
 [0.1468912 ]
 [0.14523229]
 [0.14513247]
 [0.14475194]
 [0.14297657]
 [0.14200713]
 [0.1419889 ]
 [0.14085594]
 [0.14039254]
 [0.13849622]
 [0.13157618]
 [0.13011341]
 [0.12975036]
 [0.12698154]
 [0.12666552]
 [0.12

[[0.7192773 ]
 [0.7137333 ]
 [0.6037284 ]
 [0.40515745]
 [0.36051756]
 [0.32473668]
 [0.3187048 ]
 [0.3181896 ]
 [0.26549923]
 [0.25040957]
 [0.2476749 ]
 [0.23605415]
 [0.23283432]
 [0.22894518]
 [0.22017029]
 [0.21644844]
 [0.21273087]
 [0.21036014]
 [0.20103183]
 [0.19491611]
 [0.18975961]
 [0.18774147]
 [0.18643092]
 [0.18638909]
 [0.18476972]
 [0.18114431]
 [0.18050417]
 [0.1777945 ]
 [0.1760567 ]
 [0.16475894]
 [0.16303733]
 [0.16262658]
 [0.16253926]
 [0.16176057]
 [0.16070941]
 [0.1595328 ]
 [0.15808836]
 [0.15691532]
 [0.15677105]
 [0.15607943]
 [0.15363117]
 [0.15234405]
 [0.15188879]
 [0.14949626]
 [0.14940386]
 [0.14931235]
 [0.14908274]
 [0.14760092]
 [0.1437318 ]
 [0.14350185]
 [0.1429208 ]
 [0.1424842 ]
 [0.1423285 ]
 [0.14121264]
 [0.14116274]
 [0.13929085]
 [0.13840324]
 [0.13777351]
 [0.1356156 ]
 [0.13407056]
 [0.1326097 ]
 [0.13166046]
 [0.13084038]
 [0.12993649]
 [0.12903543]
 [0.12893036]
 [0.12825434]
 [0.12472158]
 [0.12397268]
 [0.12392223]
 [0.12361016]
 [0.12

[[0.72792846]
 [0.7113884 ]
 [0.5725665 ]
 [0.5678995 ]
 [0.38666394]
 [0.36527956]
 [0.2941594 ]
 [0.28686342]
 [0.28161237]
 [0.27307966]
 [0.2712496 ]
 [0.2696066 ]
 [0.24474496]
 [0.238775  ]
 [0.22731182]
 [0.2252245 ]
 [0.22344188]
 [0.2227525 ]
 [0.21902424]
 [0.21312056]
 [0.20692006]
 [0.20312914]
 [0.20245454]
 [0.19613323]
 [0.19176212]
 [0.19143698]
 [0.19111554]
 [0.1863247 ]
 [0.18245782]
 [0.18092498]
 [0.17889121]
 [0.17623799]
 [0.1756359 ]
 [0.17493679]
 [0.17419359]
 [0.16967377]
 [0.16914314]
 [0.16875073]
 [0.16801323]
 [0.16403975]
 [0.16058356]
 [0.15742368]
 [0.15681402]
 [0.14800724]
 [0.14727546]
 [0.14711076]
 [0.14517175]
 [0.14291866]
 [0.14265434]
 [0.14022061]
 [0.13951911]
 [0.13882467]
 [0.13869074]
 [0.13835222]
 [0.13796684]
 [0.13600022]
 [0.13561194]
 [0.13509187]
 [0.13470402]
 [0.1333123 ]
 [0.1330236 ]
 [0.13297823]
 [0.13205397]
 [0.13192786]
 [0.13119467]
 [0.13075866]
 [0.13000186]
 [0.12858452]
 [0.12800315]
 [0.12696119]
 [0.12478574]
 [0.12

[[0.729609  ]
 [0.7041451 ]
 [0.5828486 ]
 [0.52482015]
 [0.36640608]
 [0.36095732]
 [0.34063727]
 [0.30620372]
 [0.30008724]
 [0.29985738]
 [0.29280427]
 [0.27852124]
 [0.2522687 ]
 [0.2281633 ]
 [0.22033854]
 [0.21468857]
 [0.2070939 ]
 [0.20391211]
 [0.19867384]
 [0.19708538]
 [0.19701976]
 [0.19251077]
 [0.18726999]
 [0.18704109]
 [0.18673593]
 [0.1858566 ]
 [0.18542843]
 [0.1820292 ]
 [0.18176839]
 [0.17174152]
 [0.1686703 ]
 [0.16735563]
 [0.16350661]
 [0.16174838]
 [0.16171482]
 [0.15971558]
 [0.15900624]
 [0.15565957]
 [0.15440424]
 [0.15372418]
 [0.15269001]
 [0.15232897]
 [0.15193474]
 [0.14981075]
 [0.14768985]
 [0.1444663 ]
 [0.1422765 ]
 [0.14120193]
 [0.14050281]
 [0.14037986]
 [0.14019915]
 [0.13887754]
 [0.13728017]
 [0.13700601]
 [0.13584906]
 [0.13350719]
 [0.13341357]
 [0.13309567]
 [0.13197382]
 [0.1319139 ]
 [0.1310736 ]
 [0.13050672]
 [0.13041396]
 [0.12884925]
 [0.12503898]
 [0.12478233]
 [0.12319501]
 [0.12271924]
 [0.12227296]
 [0.12057815]
 [0.12001098]
 [0.11