# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.19.2'

In [3]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/lpianta/anaconda3/envs/machine_learning/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/lpianta/anaconda3/envs/machine_learning/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/lpianta/anaconda3/envs/machine_learning/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/lpianta/anaconda3/envs/machine_learning/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/lpianta/anaconda3/envs/machine_learning/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/lpianta/anaconda3/envs/machine_learning/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/lpianta/anaconda3/envs/machine_learning/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [5]:
# arrayname.size
vector.size

10

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
vector1 = np.zeros(10)
vector1[4] = 1
print(vector1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
vector2 = np.arange(10,50)
print(vector2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [9]:
vector2[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
vector_base = np.arange(0,9)
matrix = vector_base.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [11]:
arr = np.array([1,2,0,0,4,0])
np.where(arr != 0)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
identity_3x3 = np.identity(3)
print(identity_3x3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.random((3, 3, 3))

array([[[0.47665106, 0.52913635, 0.98482386],
        [0.06174775, 0.90022107, 0.77256328],
        [0.43642387, 0.87066115, 0.84568154]],

       [[0.19176085, 0.30097407, 0.2855645 ],
        [0.02491712, 0.60286252, 0.57202399],
        [0.71514569, 0.13530434, 0.7665569 ]],

       [[0.05518172, 0.81617079, 0.35107242],
        [0.78713853, 0.50039991, 0.58657064],
        [0.3812419 , 0.29026474, 0.75036659]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
arr_10x10 = np.random.random((10, 10))
print(np.max(arr_10x10))
print(np.min(arr_10x10))

0.9934960303292497
0.008763034265977354


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
rand_vector = np.random.random((30))
print(np.mean(rand_vector))

0.5475159342833436


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
arr_1_0 = np.ones((10, 10))
arr_1_0[1:-1, 1:-1] = 0
print(arr_1_0)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [17]:
arr_to_fill = np.ones((4, 4))
np.pad(arr_to_fill, 1)


array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
diag_arr = np.diag((1,2,3,4), -1)
print(diag_arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
checkerboard_arr = np.full((8,8), 1)
checkerboard_arr[1::2, ::2] = 0
checkerboard_arr[::2, 1::2] = 0
print(checkerboard_arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [21]:
arr_6_7_8 = np.full((6,7,8), 1)
np.unravel_index(99, arr_6_7_8.shape)

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
np.tile([[1,0], [0,1]],  (4, 4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
random_5x5 = np.random.random((5,5))
norm = np.linalg.norm(random_5x5)
random_norm = random_5x5  / norm
print(random_norm)

[[0.17459184 0.1328708  0.02964102 0.15580202 0.32629648]
 [0.1551176  0.15580132 0.01489366 0.28983726 0.31722935]
 [0.18871068 0.16378599 0.25922485 0.10030892 0.12311632]
 [0.11147156 0.23279655 0.10466831 0.20476181 0.27813845]
 [0.30225873 0.1921021  0.03015595 0.17529239 0.27463501]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
# I think I didn't understand the quesiton properly

np.dtype([("R", np.ubyte, 1), ("G", np.ubyte, 1), ("B", np.ubyte, 1), ("A", np.ubyte, 1)])

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
random_5x3 = np.random.random((5,3))
random_3x2 = np.random.random((3,2))
print(np.dot(random_5x3, random_3x2))
print(random_5x3 @ random_3x2)

[[0.86019272 0.26822204]
 [0.42246338 0.42089812]
 [0.61942322 1.02609019]
 [0.33138281 0.4898478 ]
 [0.36842346 0.42761252]]
[[0.86019272 0.26822204]
 [0.42246338 0.42089812]
 [0.61942322 1.02609019]
 [0.33138281 0.4898478 ]
 [0.36842346 0.42761252]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
arr_to_negate = np.arange(1, 10)
arr_to_negate[3:7] *= -1
print(arr_to_negate)

[ 1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
#9
#10
print(sum(range(5), -1))
print(np.sum(range(5), -1))


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
z = np.array([1, 1, 1])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
print(np.array(0) / np.array(0)) # nan
print(np.array(0) // np.array(0)) # 0
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
round_arr = np.random.random((3, 3))
np.ceil(round_arr)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
arr1 = np.arange(1, 5)
arr2 = np.arange(3, 8)
common_arr = np.intersect1d(arr1, arr2)
print(arr1, arr2, common_arr)

[1 2 3 4] [3 4 5 6 7] [3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [32]:
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [33]:
np.sqrt(-1) == np.emath.sqrt(-1)
#np.sqrt doesn't handle negative input, while np.emath.sqrt does

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [34]:
today = np.datetime64('today')
yesterday = np.datetime64('today') - 1
tomorrow = np.datetime64('today') + 1
print(today, yesterday, tomorrow)

2020-12-29 2020-12-28 2020-12-30


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [35]:
july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(july_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [36]:
a = np.full((3, 3), 1, dtype='float')
print(f'Before computation array a is: \n{a}')
b = np.full((3, 3), 2, dtype='float')
np.add(a, b, out=b)
np.negative(a, out=a)
np.divide(a, 2, out=a)
np.multiply(a, b, out=a)
print(f'After in place computation array a is:\n{a}')

Before computation array a is: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
After in place computation array a is:
[[-1.5 -1.5 -1.5]
 [-1.5 -1.5 -1.5]
 [-1.5 -1.5 -1.5]]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [37]:
random = np.random.rand(2, 5)
print(random)
random1 = random % 0
print(random1)
random2 = random // 1
print(random2)
random3 = np.floor(random)
print(random3)
random4 = np.ceil(random)
print(random4)
random5 = np.trunc(random)
print(random5)

[[0.16772816 0.99191012 0.06031156 0.01503881 0.71710681]
 [0.66645296 0.36665657 0.30704573 0.30583277 0.64370026]]
[[nan nan nan nan nan]
 [nan nan nan nan nan]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [38]:
row = np.arange(5)
matrix_5x5 = np.repeat(row, 5).reshape(5,5).T 
print(matrix_5x5)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [39]:
# will come back to this when I'll know something about generator :)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [40]:
random_vector_10 = np.linspace(0, 1, 11, endpoint=False)[1: ]
print(random_vector_10)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [41]:
vector_sorted = np.sort(np.random.random(10))
print(vector_sorted)

[0.01320596 0.23436525 0.35699732 0.35859825 0.39216051 0.54916591
 0.60448558 0.6713019  0.93398845 0.99341333]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [50]:
small_array = np.arange(5)
np.add.reduce(small_array)

10

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [64]:
array_a = np.random.random_integers(10, size=10)
array_b = np.random.random_integers(10, size=10)
print(array_a)
print(array_b)
checker_array = array_a == array_b
equal = checker_array.all()
print(equal)

[ 8  9  2  8  4  4  4  9  5 10]
[ 8  5  1  7 10  5  8  6  8  9]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [68]:
immutable_array = np.random.random(10)
immutable_array.flags.writeable = False
immutable_array[1] = 7

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [91]:
random_10x2 = np.random.random((10, 2))
x_coord = random_10x2[:,0]
y_coord = random_10x2[:,1]
r = np.sqrt(x_coord**2 + y_coord**2)
theta = np.arctan(y_coord / x_coord)
polar = np.column_stack((r, theta))
print(polar)

[[0.45563578 0.46090697]
 [0.78470404 0.5663438 ]
 [1.27078252 0.66741606]
 [0.63534124 0.0332508 ]
 [0.93069886 0.23486661]
 [0.43599809 1.15242316]
 [0.73583131 1.37786967]
 [0.97736256 0.29783113]
 [0.95574774 1.18568761]
 [0.81908425 0.04024195]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [101]:
random_vect = np.random.random(10)
print(random_vect)
random_vect[random_vect.argmax()] = 0
print(random_vect)

[0.43245454 0.38085677 0.69702112 0.8767688  0.92162155 0.63484386
 0.61585522 0.04791984 0.30351038 0.41560673]
[0.43245454 0.38085677 0.69702112 0.8767688  0.         0.63484386
 0.61585522 0.04791984 0.30351038 0.41560673]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [106]:
structured_array = np.array([(np.linspace(0, 1, 10)), (np.linspace(0, 1, 10))], dtype=[('x', float), ('y', float)])
structured_array

array([[(0.        , 0.        ), (0.11111111, 0.11111111),
        (0.22222222, 0.22222222), (0.33333333, 0.33333333),
        (0.44444444, 0.44444444), (0.55555556, 0.55555556),
        (0.66666667, 0.66666667), (0.77777778, 0.77777778),
        (0.88888889, 0.88888889), (1.        , 1.        )],
       [(0.        , 0.        ), (0.11111111, 0.11111111),
        (0.22222222, 0.22222222), (0.33333333, 0.33333333),
        (0.44444444, 0.44444444), (0.55555556, 0.55555556),
        (0.66666667, 0.66666667), (0.77777778, 0.77777778),
        (0.88888889, 0.88888889), (1.        , 1.        )]],
      dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)